### PR TITLE
feat(#2597): allow pyarrow.dataset.Expression in filters kwarg

### LINKED ISSUE #2597: Allow `pyarrow.dataset.Expression` in `filters` kwarg of `deltalake.DeltaTable.to_pyarrow_table`
# Description

I would like to have more flexibility in using the `filters` kwarg in the method `to_pyarrow_table`, in particular by providing directly a `pyarrow.dataset.Expression`.

**Use Case**
In my use case, this is due to the fact that I want to be able to filter out null values, particularly by using a version of this issue:
- https://github.com/apache/arrow/issues/34504
and, in order to be able to do this without using some exotic mocking, I would like to directly pass the Expression.

**Related Issue(s)**
Also, note that this PR might be an occasion to reduce code duplication by removing this function:
https://github.com/delta-io/delta-rs/blob/f0416921a3814a33ea1b3796a2a1468f8c76ca3d/python/deltalake/table.py#L333-L350
in favour of this:
https://github.com/apache/arrow/blob/69e8a78c018da88b60f9eb2b3b45703f81f3c93d/python/pyarrow/parquet/core.py#L135-L199

### PR DESCRIPTION
**Pull request by giacomorebecchi**
# Description

Allow `pyarrow.dataset.Expression` in `filters` kwarg of `deltalake.DeltaTable.to_pyarrow_table` and `deltalake.DeltaTable.to_pandas` methods, and remove code dupllication in favor of the pyarrow implementation.

# Related Issue(s)
- closes #2597

### CODE REVIEW

**Comment by giacomorebecchi** [comment]
@ion-elgreco fixed both errors that were spotted in the [actions run](https://github.com/delta-io/delta-rs/actions/runs/9518584505), sorry for overlooking them!

**Comment by roeap** [comment]
looks like we need to add a few type hints to the pyarrow pyi files (in this repo) for linting to pass.

**Comment by giacomorebecchi** [comment]
> looks like we need to add a few type hints to the pyarrow pyi files (in this repo) for linting to pass.

Please let me know if my last commit works, thanks for your patience!

**Review by ion-elgreco — DISMISSED** [review]
Nice change!

**Review by ion-elgreco — APPROVED** [review]

**Pull request merged**
