### PR TITLE
 HDFS storage support via datafusion-objectstore-hdfs

### LINKED ISSUE #300: hdfs support
# Description
HDFS storage support.

**Use Case**
A significant portion of companies dealing with big data uses HDFS as the backend storage solution of choice for long-term persistent data storage and processing. Having this would be very beneficial for the place I currently work at.

### PR DESCRIPTION
**Pull request by iajoiner**
# Description
The description of the main changes of your pull request
This is basically the continuation of #1273 (really thanks @yjshen for your contributions! The work is all his..I'm just the guy who tries to get it merged!). I addressed the comments from @wjones127.
# Related Issue(s)

# Documentation

### CODE REVIEW

**Comment by iajoiner** [comment]
@yjshen Please check out the integration tests: https://github.com/delta-io/delta-rs/actions/runs/4684975786/jobs/8301645920?pr=1279

There are plenty of `java.io.FileNotFoundException`s. However all the HDFS tests nominally passed. Is this intended behavior?

**Comment by iajoiner** [comment]
Looks like the errors are really just us not being able to read non-parquet files in Delta when reading Parquet files. So I guess they are ok?

**Review by rtyler — APPROVED** [review]
From my perspective this looks ready to merge. I would like @wjones127 to click the green button though since he had comments on the original pull request

**Comment by rtyler** [comment]
@iajoiner please merge `main` to resolve the conflicts

**Comment by iajoiner** [comment]
@rtyler Really thanks! I just merged `main` and there are no conflicts haha.

**Review by wjones127 — APPROVED** [review]
Thanks for adding tests @iajoiner! This looks good to me 👍

**Pull request merged**
