### PR TITLE
docs: update changelog for 0.9.0 release

### LINKED ISSUE #1238: Release delta-rs `0.9.0` (next release after `0.8.0`)
Follow on from #1184:
- Planned Release and Publish to crates.io: 2023-04-06

Items:

- [x] PR to update version and CHANGELOG:
- [ ] Update version to `XXXX` and add changelog
- [ ] Release candidate created:
- [ ] Release to crates.io:

See full list here:
https://github.com/delta-io/delta-rs/compare/rust-v0.8.0...main
cc @houqp @wjones127 @fvaleye @rtyler @roeap @xianwill @mosyp

### PR DESCRIPTION
**Pull request by iajoiner**
# Description
The description of the main changes of your pull request
Update changelog for Rust 0.9.0 release
# Related Issue(s)

Closes #1238.
# Documentation

### CODE REVIEW

**Comment by roeap** [comment]
@rtyler  and I worked on the datafusion update, which is ready for review / merge. Since updating arrow / datafusion is a key enabler for downstream consumers to use delta-rs, mabe we can try to include that PR?

**Comment by iajoiner** [comment]
@roeap Sure!

**Comment by rtyler** [comment]
@iajoiner at the moment yes, #1249'is it

**Comment by iajoiner** [comment]
@rtyler Sure. Added haha. I wonder when #1249 can be merged haha.

**Comment by rtyler** [comment]
Probably as soon as Will sees it 😅
------- Original Message -------

**Comment by iajoiner** [comment]
@rtyler Haha. Now we are unblocked!

**Review by rtyler — APPROVED** [review]

**Pull request merged**
