### PR TITLE
Add sample `CHANGELOG` and changelog generation/update script

### LINKED ISSUE #996: Automatically generate and update changelogs
# Description
Automatically generate and update changelogs
**Use Case**
Helps with our monthly release

### PR DESCRIPTION
**Pull request by iajoiner**
# Description
Add a sample `CHANGELOG.md` as well as the script that generates/updates `CHANGELOG.md` and `CHANGELOG-old.md`

Closes #996.

Features:
1. Contributions with the label "dependencies" which are abundant, are always made by dependabot and are not very useful in a changelog have been ignored.
2. Ignore tags with different languages (e.g. ignore any Python tag when producing the changelog from Rust 0.5.0 to Rust 0.6.0).

Features in future PRs:
1. Filter out contributions that are from unrelated languages which will probably benefit from autolabelling of  PRs.

### CODE REVIEW

**Review by roeap — DISMISSED** [review]
Really looking forward to doing more frequent, higher quality releases :), thanks!

You would have to rebase or merge once for me to trigger CI.

**Comment by roeap** [comment]
@iajoiner - i was about to merge this, when i realized this would bump the rust version to `0.6.0`. Is this intentional? And if so, would the script update the log once we do the actual release?

**Comment by iajoiner** [comment]
@roeap This is really just a preview of what will happen once we do actually have a release. However we do need to add historical changelogs. In order for Python changes between a Python release and the Rust release after that to not be included into the Rust release and vice versa we need to get autolabeling done first.

**Comment by roeap** [comment]
makes sense :) - i took the liberty to convert this to draft, hope that is OK.

**Comment by iajoiner** [comment]
Once #1030 is merged I will improve this one.

**Pull request closed without merging**
