### PR TITLE
chore: upgrade to datafusion 43

### PR DESCRIPTION
**Pull request by ion-elgreco**
# Description
Bump kernel

 - closes https://github.com/delta-io/delta-rs/issues/2850

### CODE REVIEW

**Comment by rtyler** [comment]
We need Datafusion to upgrade as well before we can do this. I have some patches to make the latest datafusion work but we're blocked on them to adopt the newest arrow and kernel

**Comment by Xuanwo** [comment]
Hi, datafusion has been released. Let's rock!

**Comment by alamb** [comment]
Thank you @ion-elgreco  -- let me know if there is anything I can to do help with this PR (e.g. I could work on updating the code to use non deprecated APIs in the core for parquet statistics...)

**Comment by ion-elgreco** [comment]
Hey @alamb, I am not working on this atm, but @rtyler has picked it up from here

**Comment by ion-elgreco** [comment]
@alamb there seems to be a regression in DF, see https://github.com/delta-io/delta-rs/actions/runs/10959345721/job/30431504526?pr=2886#step:7:948.  

A literal with a list is creating a dtype list with inner type using the name "item", we however have our data internally read according to the parquet spec, so that when we write the parquet files are meeting the field naming of the spec.

I had a quick glance at the Changelog but can't really pinpoint where this change may have occurred, do you have any ideas?

```
DFSchema { inner: 
Schema { fields: [
Field { name: "items_in_bucket", data_type: List(Field { name: "element", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, 
new schema: 
DFSchema { inner: Schema { fields: [
Field { name: "items_in_bucket", data_type: List(Field { name: "item", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} },
```

**Comment by alamb** [comment]
> @alamb there seems to be a regression in DF, see https://github.com/delta-io/delta-rs/actions/runs/10959345721/job/30431504526?pr=2886#step:7:948.
> 
> A literal with a list is creating a dtype list with inner type using the name "item", we however have our data internally read according to the parquet spec, so that when we write the parquet files are meeting the field naming of the spec.
> 

It sounds somewhat similar to a discussion happening here about nullability (but I think field name is similar in terms of how it is treated): https://github.com/apache/datafusion/pull/11989#issuecomment-2360601240

**Comment by rtyler** [comment]
@alamb thanks for following up! I feel a little sheepish :sheep: insofar that my internal CI showed these errors weeks ago in my integration testing between datafusion `main` with `delta-rs` main, I just didn't have the time to triage them like @ion-elgreco has :smile: 

I've subscribed to the issue you created and can help testing if necessary! Depending on my availability this weekend I can try fixing it in datafusion too :thinking:

**Comment by matthewmturner** [comment]
Hi there - I believe a [fix](https://github.com/apache/datafusion/issues/12687) was implemented in datafusion and this PR is not blocked any longer.

**Comment by ion-elgreco** [comment]
> Hi there - I believe a [fix](https://github.com/apache/datafusion/issues/12687) was implemented in datafusion and this PR is not blocked any longer.

It's not yet released though

**Comment by rtyler** [comment]
I can confirm that the latest datafusion main passes tests in CI :partying_face:

**Comment by alamb** [comment]
> fix

I filed https://github.com/apache/datafusion/issues/12813 to consider releasing a patch version of DataFusion

**Comment by Xuanwo** [comment]
Hi, is the title of this PR incorrect? We're going to DF 42, right?

**Comment by Xuanwo** [comment]
> The title is not incorrect 😆 There will be no deltalake release with datafusion 42 because of the regression identified. Additionally it doesn't look like the datafusion community is going to create a 42.1.0, which means we have no choice but to skip 42 and wait for 43 😭

Understood. It's somewhat sad that our efforts to upgrade to Arrow 53 have been blocked by this issue.

**Comment by alamb** [comment]
> Additionally it doesn't look like the datafusion community is going to create a 42.1.0, which means we have no choice but to skip 42 and wait for 43 😭

One alternate would be for someone to help us make a 42.1.0 (no one volunteered on https://github.com/apache/datafusion/issues/12813)

**Comment by Xuanwo** [comment]
> One alternate would be for someone to help us make a 42.1.0 (no one volunteered on apache/datafusion#12813)

Hi, I'm willing to help for this.

**Comment by alamb** [comment]
> > One alternate would be for someone to help us make a 42.1.0 (no one volunteered on [apache/datafusion#12813](https://github.com/apache/datafusion/issues/12813))
> 
> Hi, I'm willing to help for this.

Update here is that we have found some help and will try and do this release sometime later this week or early next week

**Comment by Xuanwo** [comment]
Updates: we only need one more binding vote to make this release.

**Comment by alamb** [comment]
> Updates: we only need one more binding vote to make this release.

❤️  -- I think we have the votes, I am just now waiting for the 72 hour timeline to elapse and then I will publish the release

**Comment by Xuanwo** [comment]
> ❤️ -- I think we have the votes, I am just now waiting for the 72 hour timeline to elapse and then I will publish the release

That's great. I've been waiting for this for so long. Happy that I can contribute to pushing this forward.

**Comment by alamb** [comment]
https://crates.io/crates/datafusion/42.1.0 is now available

**Comment by ion-elgreco** [comment]
There is still one failing test, which should be easy to fix. I don't have access to my PC though to resolve it

**Comment by Xuanwo** [comment]
> There is still one failing test, which should be easy to fix. I don't have access to my PC though to resolve it, @Xuanwo would you perhaps be able to push to this branch?

I would really like to, but I'm not a committer for delta-rs. Perhaps we should seek assistance from @rtyler.

**Comment by alamb** [comment]
> > There is still one failing test, which should be easy to fix. I don't have access to my PC though to resolve it, @Xuanwo would you perhaps be able to push to this branch?
> 
> I would really like to, but I'm not a committer for delta-rs. Perhaps we should seek assistance from @rtyler.

You could potentially make a PR (in the https://github.com/ion-elgreco/delta-rs fork) that targets this branch that @ion-elgreco  could merge in

However, isn't it (very) late in your timezone 💤

**Comment by hntd187** [comment]
@ion-elgreco I fixed your test you just have to merge https://github.com/ion-elgreco/delta-rs/pull/4

**Comment by Xuanwo** [comment]
> However, isn't it (very) late in your timezone 💤 🤔

Haha, indeed. This was the last message I sent yesterday. Thank you @hntd187 for making progress.

**Comment by ion-elgreco** [comment]
Unfortunately still one failure: https://github.com/delta-io/delta-rs/actions/runs/11429877833/job/31796752448#step:5:858

**Comment by Xuanwo** [comment]
Hi, there appears to be a strange issue: `items_in_bucket` is a list. Its field used to be named `element`, but it has now been changed to `item`.

Any ideas to this? cc @ion-elgreco @alamb

**Comment by ion-elgreco** [comment]
> Hi, there appears to be a strange issue: `items_in_bucket` is a list. Its field used to be named `element`, but it has now been changed to `item`.
> 
> Any ideas to this? cc @ion-elgreco @alamb 

We switched in kernel-rs to use parquet structure for these arrow types. But Datafusion seems to play nicely anymore with two types being the same except for the field name

**Comment by alamb** [comment]
> > Hi, there appears to be a strange issue: `items_in_bucket` is a list. Its field used to be named `element`, but it has now been changed to `item`.
> > Any ideas to this? cc @ion-elgreco @alamb
> 
> We switched in kernel-rs to use parquet structure for these arrow types. But Datafusion seems to not play nicely anymore with two types being the same except for the field name

I have some thoughts I will write down tomorrow morning. Hopefully I can help here too

**Comment by nicklan** [comment]
> > Hi, there appears to be a strange issue: `items_in_bucket` is a list. Its field used to be named `element`, but it has now been changed to `item`.
> > Any ideas to this? cc @ion-elgreco @alamb
> 
> We switched in kernel-rs to use parquet structure for these arrow types. But Datafusion seems to not play nicely anymore with two types being the same except for the field name

Yeah, we switched to `element` [here](https://github.com/delta-incubator/delta-kernel-rs/pull/301) as it matches the parquet [`spec`](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#lists).

Not sure if I can help resolve this, but let me know if there's anything we can do to help.

**Comment by rtyler** [comment]
I don't have a solution yet, but I've been working on replicating the python test failure in a more narrow :crab: unit test. :hammer: :hammer: :hammer:

**Comment by alamb** [comment]
Here is a proposal upstream to make this error configurable; https://github.com/apache/datafusion/issues/13065

If there is general agreement on this approach I can make a PR and another Datafusion release)

**Comment by ion-elgreco** [comment]
> Here is a proposal upstream to make this error configurable; https://github.com/apache/datafusion/issues/13065
> 
> If there is general agreement on this approach I can make a PR and another Datafusion release)

Isn't it better that the optimizer coerces the schema correctly?

**Comment by alamb** [comment]
> > Here is a proposal upstream to make this error configurable; [apache/datafusion#13065](https://github.com/apache/datafusion/issues/13065)
> > If there is general agreement on this approach I can make a PR and another Datafusion release)
> 
> Isn't it better that the optimizer coerces the schema correctly?

Yes, you are right. I should have made it clear the idea for an "ignore the error" flag was meant to be temporary -- I tried to clarify in https://github.com/apache/datafusion/issues/13065#issuecomment-2430035396

**Comment by alamb** [comment]
I am working to make a 42.2.0 release so that maybe this PR could be merged. Are you willing to test out the 42.2.0 RC?

https://github.com/apache/datafusion/pull/13191

**Comment by rtyler** [comment]
I've merged these changes into an internal test branch with your datafusion fork and will let you know what Jenkins has to say about it :tophat:

**Comment by rtyler** [comment]
Hah, some tests passed in `main` and CI was going and the branch was merged and deleted underneath the pipeline. 

Anywho, I think it looks promising from the preliminary tests

**Comment by alamb** [comment]
> Hah, some tests passed in `main` and CI was going and the branch was merged and deleted underneath the pipeline.
> 
> Anywho, I think it looks promising from the preliminary tests

Thanks @rtyler  -- I will proceed with making the real release then.

**Comment by ion-elgreco** [comment]
@alamb is there any change still required? Because I still see failed tests

**Comment by alamb** [comment]
> @alamb is there any change still required? Because I still see failed tests

I don't know to be honest.

**Comment by matthewmturner** [comment]
Hi there - just doing a pulse check on this PR.  It looks like its been updated to DataFusion v43 but I still see several failing CI checks.  Are there new regressions in v43?

**Comment by hntd187** [comment]
@matthewmturner I just did some more fixes on our side, I noticed we still have what appears to be a regression https://github.com/delta-io/delta-rs/actions/runs/11860379826/job/33055504796?pr=2886#step:4:2436 could someone take a look at this?

**Comment by timsaucer** [comment]
I think the problem is that the projected schema for array types is changing the field name for the elements of the array from "element" to "item". I have seen this before, but I'm not sure exactly where that is happening. I will try to keep digging in.

**Comment by rtyler** [comment]
This last test failure I believe is because of the use of the [make_array UDF](https://github.com/apache/datafusion/blob/main/datafusion/functions-nested/src/make_array.rs#L87-L100) which expects items in the array to be `item` rather than `element`. 

I'm not convinced this is a Datafusion issue per se, I'm still digging through some code to see if they've standardized on using "element" vs "item". Either way I don't want to wait for datafusion 44 to merge this change, so I'll be figuring out a workaround shortly :hugs:

**Comment by timsaucer** [comment]
Please let me know what you discover. I do expect we may release a DF 43.1.0 due to a number of changes recently to account for the new default StringView instead of String. If the root problem is on the DF side, we could potentially include it as well.

**Comment by rtyler** [comment]
@timsaucer My preference would certainly be for `make_array` to use `element` for the field name of the elements in the array :laughing:  We have adopted that because it's consistent with how Apache Parquet does things.  In this case, the test itself is using `make_array` so I'm going to update the test to create the ListArray the Good Ol Fashioned Way :tm:  and add a warning for folks sending in ListArrays with `item` element names.

**Comment by hntd187** [comment]
Is it perhaps possible to include UDFs that just let you specify and optional field name for the inner field like this? Because I know Map also gets the same treatment of "what are the inner fields called, well we call it this, they call it that." So it might just let more advanced users choose their own adventure instead of having to go back and forth.

**Comment by rtyler** [comment]
I have rebased on `main` and consolidated a couple commits. This should be ready to merge if the actions go green @hntd187

**Comment by rtyler** [comment]
I have been deep in the datafusion println!() hell and I believe that there may be something about the optimizer which is expecting anything that is a List() to have a field type of item.

Working through this with gdb and prints a'plenty I am still narrowing down where or how this might be happening. The `optimize_projections` rule is definitely trying too use a List<field="item"> type of list in its schema despite the originating schema not having that.

I'm still not 100% sure this isn't something funky with our projections but I'm hammering away 



```
Context("Optimizer rule 'optimize_projections' failed", Context("optimize_projections", Internal("Failed due to a difference in schemas, original schema: DFSchema { inner: Schema { fields: [Field { name: \"id\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"temp\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"items\", data_type: List(Field { name: \"element\", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"__delta_rs_update_predicate\", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }, field_qualifiers: [Some(Bare { table: \"target\" }), Some(Bare { table: \"target\" }), None, None], functional_dependencies: FunctionalDependencies { deps: [] } }, new schema: DFSchema { inner: Schema { fields: [Field { name: \"id\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"temp\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"items\", data_type: List(Field { name: \"item\", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: \"__delta_rs_update_predicate\", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }, field_qualifiers: [Some(Bare { table: \"target\" }), Some(Bare { table: \"target\" }), None, None], functional_dependencies: FunctionalDependencies { deps: [] } }")))
```

**Comment by rtyler** [comment]
Just disabling the OptimizeProjections rule and all tests pass :melting_face: :face_with_spiral_eyes:

**Comment by rtyler** [comment]
Okay here's what I think is happening. In the resolution of Projections the List<name=element> that we pass in is getting turned into an Expr and then inside the OptimizeProjections it tries to turn that back into a Field but it's becoming a List<name=item> there.

```
 DEBUG datafusion_expr::utils                                      > exprlist_to_fields schema: DFSchema { inner: Schema { fields: [Field { name: "id", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }
, Field { name: "temp", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "items", data_type: List(Field { name: "element", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered
: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "__delta_rs_update_predicate", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata
: {} }, field_qualifiers: [Some(Bare { table: "target" }), Some(Bare { table: "target" }), Some(Bare { table: "target" }), None], functional_dependencies: FunctionalDependencies { deps: [] } }
 DEBUG datafusion_expr::utils                                      > fall through for Column(Column { relation: Some(Bare { table: "target" }), name: "id" })
 DEBUG datafusion_expr::utils                                      > field should be: Ok((Some(Bare { table: "target" }), Field { name: "id", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }))
 DEBUG datafusion_expr::utils                                      > fall through for Column(Column { relation: Some(Bare { table: "target" }), name: "temp" })
 DEBUG datafusion_expr::utils                                      > field should be: Ok((Some(Bare { table: "target" }), Field { name: "temp", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }))
 DEBUG datafusion_expr::utils                                      > fall through for Alias(Alias { expr: Case(Case { expr: Some(Column(Column { relation: None, name: "__delta_rs_update_predicate" })), when_then_expr: [(Literal(Boolean(
true)), Literal(List([100])))], else_expr: Some(Column(Column { relation: Some(Bare { table: "target" }), name: "items" })) }), relation: None, name: "items" })
 DEBUG datafusion_expr::utils                                      > field should be: Ok((None, Field { name: "items", data_type: List(Field { name: "item", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadat$
: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }))
 DEBUG datafusion_expr::utils                                      > fall through for Column(Column { relation: None, name: "__delta_rs_update_predicate" })
 DEBUG datafusion_expr::utils                                      > field should be: Ok((None, Field { name: "__delta_rs_update_predicate", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }))
 DEBUG datafusion_expr::utils                                      > exprlist_to_fields: [(Some(Bare { table: "target" }), Field { name: "id", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), (Some(
Bare { table: "target" }), Field { name: "temp", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), (None, Field { name: "items", data_type: List(Field { name: "item", data_type: Int32, nullable: fals
e, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), (None, Field { name: "__delta_rs_update_predicate", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ord
ered: false, metadata: {} })]
```

Basically `Expr.to_field()` for this last projection is not giving us a compatible schema. That makes me believe this is a Datafusion bug which I will try to create a reproduction case for.  The short-term fix for delta-rs, in order to merge this change,j I believe is going to be to disable that optimizer rule until further notice :face_holding_back_tears:

**Comment by timsaucer** [comment]
Thank you for the analysis! I plan to work on this in the DataFusion side this week.

**Comment by rtyler** [comment]
@timsaucer I believe the error is introduced further up the optimization rules stack FWIW.

**Going into optimization**
```
Projection: target.id, target.temp, CASE __delta_rs_update_predicate WHEN Boolean(true) THEN CAST(make_parquet_array(Int64(100)) AS List(Field { name: "element", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, met
adata: {} })) ELSE target.items END AS items, __delta_rs_update_predicate
```

**After invoking simplify_expressions**
```
 DEBUG datafusion_optimizer::utils                                 > simplify_expressions:
Projection: target.id, target.temp, CASE __delta_rs_update_predicate WHEN Boolean(true) THEN List([100]) ELSE target.items END AS items, __delta_rs_update_predicate
  MetricObserver id=update_source_count
    Projection: target.id, target.temp, target.items, target.id = Int32(1) OR target.id != Int32(1) AND Boolean(NULL) AS __delta_rs_update_predicate
      TableScan: target
```


[SimplifyExpressions](https://github.com/apache/datafusion/blob/main/datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs#L644-L657) appears to erase the defined field names which only causes problems _later_ in OptimizeProjections.

I might not be qualified to fix this sticky of a bug :laughing:

**Comment by timsaucer** [comment]
FYI this does correct the error in the unit test `test_update_with_array`. I need to add unit tests in DataFusion still.
https://github.com/apache/datafusion/pull/13468

**Comment by alamb** [comment]
We plan to make another DataFusion patch release to unblock this upgrade:
- https://github.com/apache/datafusion/issues/13499

**Comment by alamb** [comment]
its-happening

**Comment by alamb** [comment]
👋  hey there -- we are starting to get ready for the DataFusion 44 release and are trying to make sure it is less disruptive to delta-rs than this past release
- https://github.com/apache/datafusion/issues/13334

@rtyler  Would it be ok if we started working on the upgrade now before the DataFusion release to test and find any potential breakages *before*?

Maybe we can make a WIP PR to this repo with a crates.io pin (similar to what i am doing in DataFusion with arrow-rs):
- https://github.com/apache/datafusion/pull/13663

If this sounds ok, I can start working on that PR

**Comment by roeap** [comment]
hey @alamb - that would not only be OK, but a great thing to do :). Happy to support if needed along the way.

**Comment by alamb** [comment]
Cool -- thanks -- I'll give it a try hopefully in the next day or two. I am sure I will need help with the python stuff

**Comment by alamb** [comment]
I haven't made any actual progress on this, but I have created a ticket to track the work: 
- https://github.com/apache/datafusion/issues/13834

**Comment by rtyler** [comment]
@alamb I had not seen this issue last week, sorry! I maintain a branch for customers with datafusion main on it, I will cherry-pick and queue up the delta-rs modifications I have shortly

**Comment by alamb** [comment]
> @alamb I had not seen this issue last week, sorry! I maintain a branch for customers with datafusion main on it, I will cherry-pick and queue up the delta-rs modifications I have shortly

No worries at all -- thank you 🙏 

I was actually about to start work on trying to upgrade DataFuson in delta.rs this morning (I have a few other things to do first) but if you have already done the work that is amazing. Thank you!!!!

**Comment by rtyler** [comment]
https://github.com/delta-io/delta-rs/pull/3073

**Comment by alamb** [comment]
> #3073

😍

**Pull request merged**
