### PR TITLE
feat: sharable reference to storage backend

### PR DESCRIPTION
**Pull request by roeap**
# Description

While working on #632 i saw that a shareable storage backend is also required for #690 - as such i decided to move this to a separate PR, to get things stared for #689.

# Related Issue(s)

# Documentation

### CODE REVIEW

**Review by wjones127 — APPROVED** [review]
Thank you for pulling this out into a separate PR. 🙌 

This looks great to me!

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
In the long run, I wonder if it would be better to add a Clone trait constraint to the StorageBackend trait instead.

**Comment by wjones127** [comment]
> In the long run, I wonder if it would be better to add a Clone trait constraint to the StorageBackend trait instead.

Is the expectation there that internally they might use an Arc so that cloning is cheap? Not sure which way is more idiomatic in Rust.

**Comment by houqp** [comment]
> Is the expectation there that internally they might use an Arc so that cloning is cheap? Not sure which way is more idiomatic in Rust.

I think using Arc internally would be the last resort if the upstream sdk client doesn't implement Clone because it incurs extra runtime overheads. All of our current storage backends should be able to derive Clone without using Arcs from a quick glance. Most of the derived clone implementation should be very cheap and if it is not it shouldn't be a problem assuming storage backend clone is a very infrequent operation. On the other hand, accessing the backend itself for read/write is a frequent runtime operation, so it's better to not force the atomic reference counter overhead everywhere only because we need infrequent cheap clones.

If clone is a frequent runtime operation, then wrapping all backend with an Arc is likely the right design choice.

We even have a very old task that talked about getting rid of the trait object constraint from storage backend entirely in https://github.com/delta-io/delta-rs/issues/257 :)

**Comment by wjones127** [comment]
> On the other hand, accessing the backend itself for read/write is a frequent runtime operation, so it's better to not force the atomic reference counter overhead everywhere only because we need infrequent cheap clones.

I was under the impression the increment / decrement overhead just happened in `Arc::clone()` and `Arc::drop()`, and thus we shouldn't have any overhead within objects, just a little bit when we are creating new structs where we need to pass a reference to the filesystem. Is it called also when calling methods of `T` on an `Arc<T>`?

**Comment by houqp** [comment]
> I was under the impression the increment / decrement overhead just happened in Arc::clone() and Arc::drop(), and thus we shouldn't have any overhead within objects,

I was wrong and you are right in this case @wjones127  :) Accessing the heap object should have no overhead, Arc's overhead only comes from clone and drop. So in this case, it won't make a difference for us because clone is a very infrequent operation.

**Pull request merged**
