### PR TITLE
docs: move dynamo docs into new docs page

### PR DESCRIPTION
**Pull request by ion-elgreco**
# Description
Adds the dynamo docs into our new docs, within the python write_deltalake I am pointing to the guide since it's quite extensive and only for S3 users.

@rtyler @dispanser

### CODE REVIEW

**Comment by MrPowers** [comment]
LGTM, but I think we might want to organize this content a bit differently.

Here's the current structure:

* Usage
  * Writing a table

Here's what you're proposing:

* Usage
  * Writing
    * Writing to S3 with S3 locking provider

We may want to organize the content as follows:

* Clouds
  * AWS
    * S3 locking with DynamoDB
    * AWS Lambda
    * AWS Sagemaker
  * Azure
    * Azure functions

**Comment by ion-elgreco** [comment]
We could reorganize that a bit later, currently I am only moving some docs that landed by accident in the sphinx back in to the current docs.

In terms of terminology, I would say object store probably better and S3 API is also used outside of AWS so maybe best to not to mention AWS specifically here

**Comment by MrPowers** [comment]
@ion-elgreco - yea, in general Google doesn't like when pages get moved to new URLs.  Perhaps we can add redirects for the links we're breaking? https://github.com/mkdocs/mkdocs-redirects

**Comment by ion-elgreco** [comment]
@MrPowers a nice one, let's do that in the next reorganisation of the pages.

Then I'll also write a small example where you write from Azure

**Review by MrPowers — APPROVED** [review]
LGTM

**Pull request merged**
