### PR TITLE
Add datafusion examples to docs

### LINKED ISSUE #515: Add documentation for using Delta Table with datafusion
# Description
As a user of delta-rs I would like to see examples of how to use the datafusion extension to query delta tables in the rust docs.

This would include examples for querying both local and s3 delta tables.

**Use Case**

**Related Issue(s)**

### PR DESCRIPTION
**Pull request by matthewmturner**
# Description
The description of the main changes of your pull request

# Related Issue(s)

closes #515
# Documentation

### CODE REVIEW

**Comment by matthewmturner** [comment]
Started putting together the docs, based on test in `delta_datafusion.rs`.  I havent been able to actually get querying delta tables to work locally yet, but wanted to publicize the work in case any comments.

**Comment by matthewmturner** [comment]
@houqp can delta tables be queried with the datafusion python bindings?  i can add something for that as well.

**Comment by matthewmturner** [comment]
and this might be a silly question, but why does the datafusion feature have the `ext` suffix but `s3` and `azure` dont?

**Comment by matthewmturner** [comment]
i looked into this on the python side and it seems that the `ExecutionContext` is missing the `register_table` method that is used in rust to query `DeltaTables`.  I'll create an issue there to add that functionality as it would be nice to query from python.

now im going to try querying s3 `DeltaTable` in rust and adding docs for that then i think this should be good.

**Comment by houqp** [comment]
> @houqp can delta tables be queried with the datafusion python bindings? i can add something for that as well.

Probably not yet because I don't think we support taking a list of file paths yet in the current table provider implementation :(

> and this might be a silly question, but why does the datafusion feature have the ext suffix but s3 and azure dont?

Because the `datafusion` feature conflicts with the `datafusion` crate name. But I learned later that we could use optional dependencies as features directly. I haven't tested it myself, if this works, it would be better to use `datafusion` as the feature name going forward in our docs.

**Comment by matthewmturner** [comment]
> Probably not yet because I don't think we support taking a list of file paths yet in the current table provider implementation :(
> 
@qphou can you expand on that? I thought since you can query with datafusion in Rust it was just a matter of exposing that via Python with something like a `register_table` on context.

**Comment by matthewmturner** [comment]
@houqp ready for review

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
Thank you @matthewmturner !

**Pull request merged**
