### PR TITLE
Add docs for ADLS Gen2.

### PR DESCRIPTION
**Pull request by thovoll**
# Description
Add docs that describe how to create an ADLS Gen2 storage account

# Related Issue(s)
#60

### CODE REVIEW

**Comment by thovoll** [comment]
@roeap @rtyler @houqp please take a look. Thanks!

**Review by houqp — APPROVED** [review]
nitpick, @thovoll do you mind moving it into a new `/docs` folder? I think we can use that folder as a starting place to build out an overall delta-rs project documentation and eventually generate an official website from it.

**Comment by thovoll** [comment]
Thanks @houqp, will do!

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
Thanks @thovoll !

**Comment by thovoll** [comment]
Thanks @houqp!

**Pull request merged**
