### PR TITLE
[WIP] Move version field into DeltaTableState struct

### PR DESCRIPTION
**Pull request by explicite**
# Description
The description of the main changes of your pull request

# Related Issue(s)
#390 

# Documentation
//TODO

### CODE REVIEW

**Comment by houqp** [comment]
@explicite let us know if you need any help in finishing up this PR :)

**Comment by roeap** [comment]
@explicite - are you planning on finishing this? If not, I may just include it in #632, since it is quite helpful over there.

**Comment by houqp** [comment]
@roeap let's include it in #632 then if you need it there.

**Comment by roeap** [comment]
closed in favour of #649

**Pull request closed without merging**
