### PR TITLE
feat(python): expose `add constraint` operation

### PR DESCRIPTION
**Pull request by ion-elgreco**
# Description
Currently limited to a single constraint at once. I didn't want to chance the function defintion for this so I just check if more than 1 constraint is passed it will raise an error. Once we have the multiple constraints possibility in Rust, I can simply remove this size check.

### CODE REVIEW

**Comment by ion-elgreco** [comment]
Errors will be fixed if we merge this refactor first: https://github.com/delta-io/delta-rs/pull/1979

**Review by roeap — APPROVED** [review]
Nice! Should we also add an issue to track documenting this feature?

**Comment by ion-elgreco** [comment]
@roeap regarding the single constraint addition per time?

**Comment by roeap** [comment]
@ion-elgreco - yes, not sure that there is a question o.a. here ... 😆

**Comment by ion-elgreco** [comment]
@roeap :) I'll create an issue for it.

@hntd187  mentioned he would add that possibility

**Pull request merged**
