### PR TITLE
add MANIFEST.in

### PR DESCRIPTION
**Pull request by raybellwaves**
This includes the license in the build (cc. https://github.com/conda-forge/staged-recipes/pull/16045)

### CODE REVIEW

**Comment by rtyler** [comment]
@raybellwaves would you please add some comments into the file about its purpose/etc? As somebody who barely understands what or why conda is, it would be helpful to understand the purpose before we merge this small addition :smile:

**Comment by raybellwaves** [comment]
> @raybellwaves would you please add some comments into the file about its purpose/etc? As somebody who barely understands what or why conda is, it would be helpful to understand the purpose before we merge this small addition 😄

Ha no problem. I should have added this info my first post. TBH it's relatively new to me.

# What is a MANIFEST.in file?

https://packaging.python.org/guides/using-manifest-in/ gives info about the purpose of a MANIFEST.in file. https://packaging.python.org/guides/using-manifest-in/#manifest-in-commands gives more info about the usage of the file.

# Why am I making this PR?

AFAICT when adding a package to conda-forge it asks you to check the license is packaged (https://conda-forge.org/docs/maintainer/adding_pkgs.html#packaging-the-license-manually). I clearly see the license in this repo so no issues there. I believe it's good to have a MANIFEST.in to add the license to the build (from a typical python package point of me)? However, given this isn't a pure python package I understand the MANIFEST.in may not fit. I'll let @synapticarbors chime in with more info. I know he's done this for other repos and told me about it before e.g https://github.com/conda-forge/staged-recipes/pull/13321#discussion_r529946631

**Comment by rtyler** [comment]
Thanks for all the details! Considering the packaging of wheels in `python/` using `pyo3` I'm actually not sure whether this will solve the desired problem. Perhaps @fvaleye has thoughts to share here

**Comment by houqp** [comment]
there is probably an option in https://github.com/PyO3/maturin to specify what extra files to include in the release wheel.

**Comment by fvaleye** [comment]
> Thanks for all the details! Considering the packaging of wheels in `python/` using `pyo3` I'm actually not sure whether this will solve the desired problem. Perhaps @fvaleye has thoughts to share here

Thanks for the details @raybellwaves!

@rtyler The best option for including the `LICENSE.txt` file would be to use this maturin property (https://github.com/PyO3/maturin#source-distribution):
```
[tool.maturin]
sdist-include = ["LICENSE.txt"]
```
Unfortunately, while building the Python binding, I can't include the file from the root folder ("../LICENSE.txt").
One option would be to copy/paste the LICENSE.txt file inside the python folder... 😞 

On another subject, using the `pyproject.toml` file, we could include the license as a string like this:
`
license = {file = "../LICENSE.txt"}
`

**Comment by houqp** [comment]
`pyproject.toml` is definitely the better way to go if it works :D

**Comment by fvaleye** [comment]
@raybellwaves I created another PR to include the `LICENSE.txt` file and make a reference inside the `pyproject.toml` file. The `MANIFEST.in` file is not mandatory and doesn't work with `PyO3/maturin`.

Since `PyO3/maturin` supports [PEP 621](https://www.python.org/dev/peps/pep-0621/), we will use the `pyproject.toml`.

**Comment by raybellwaves** [comment]
Thanks. Welcome to close this. Thanks for your work on the repo

**Comment by rtyler** [comment]
Superseded by #422

**Pull request closed without merging**
