### PR TITLE
fix: remove `pandas` pin

### LINKED ISSUE #1745: Support `pandas>=2`
# Description

As it says in the title.

https://github.com/delta-io/delta-rs/blob/16910304e64792410fcefeac01507fb621fc8f1e/python/pyproject.toml#L26

----

***xref:*** #1264

### PR DESCRIPTION
**Pull request by dhirschfeld**
# Description

Removes the `pandas` pin.

# Related Issue(s)

Resolves #1745

### CODE REVIEW

**Comment by dhirschfeld** [comment]
I'm just opening this draft PR to see what exactly is broken when running `pandas>=2` with the latest code on `main`

**Comment by dhirschfeld** [comment]
Grepping `pandas` in the logs only brings up 1 test, but it seems to pass:
```
tests/test_table_read.py::test_delta_table_to_pandas PASSED              [ 45%]
```
...so I'm not sure what (if anything) needs to be done?

**Comment by dhirschfeld** [comment]
It does seem to be using the latest `pandas`:
```
2023-10-20T04:45:35.6414538Z Collecting pandas
2023-10-20T04:45:35.6418511Z   Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/2f/0e/3b74e8f7c908082793adafb02753477f653ccd7e189f3ba070757d2d0e65/pandas-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
2023-10-20T04:45:35.6525331Z   Downloading pandas-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
```

**Comment by wjones127** [comment]
> ...so I'm not sure what (if anything) needs to be done?

It might have been a regression early on in Pandas 2.0 that caused us to pin. I assume we are checking with Pandas 2.1.1. Could we also check with 2.0.3? if that also passes I'm good as is.

**Comment by dhirschfeld** [comment]
```
ERROR: No matching distribution found for pandas==2.0.3; extra == "pandas"
```
That seems odd :thinking:

**Comment by roeap** [comment]
> That seems odd 🤔

seems to be related to 3.7 not supported by some dependency. we have been meaning to drop 3.7 anyhow though ...

**Comment by dhirschfeld** [comment]
> > That seems odd 🤔
> 
> seems to be related to 3.7 not supported by some dependency. we have been meaning to drop 3.7 anyhow though ...

It did go EOL at the end of June - https://devguide.python.org/versions/

**Comment by dhirschfeld** [comment]
On 3.10:
```
2023-10-20T05:30:11.2391495Z   Downloading pandas-2.0.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
```

On 3.7
```
2023-10-20T05:30:42.7552159Z Collecting pandas<=2.0.3 (from deltalake==0.12.0)
2023-10-20T05:30:42.7710445Z   Downloading pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
```

**Comment by roeap** [comment]
well ... i guess unpin and we can merge.

Worst case someone discovers the right (or rather wrong) combination of pandas / pyarrow in the wild after the next release and we have to do a patch ...

**Review by roeap — APPROVED** [review]

**Comment by dhirschfeld** [comment]
You might want to [squash-merge](https://xkcd.com/1296/) this one! 😅

**Comment by roeap** [comment]
> You might want to [squash-merge](https://xkcd.com/1296/) this one! 😅

agreed, will do 😆

**Pull request merged**
