### PR TITLE
fix: properly deserialize percent-encoded file paths of Remove actions, to make sure tombstone and file paths match

### PR DESCRIPTION
**Pull request by sigorbor**
# Description
Percent-encoded file paths of Remove actions were not properly deserialized, and when compared to active file paths, the paths didn't match, which caused tombstones to be recognized as active files (be kept in the state)

# Related Issue(s)

# Documentation

### CODE REVIEW

**Comment by sigorbor** [comment]
> @sigorbor can you add a small test?

Sure, done

**Comment by sigorbor** [comment]
@ion-elgreco @rtyler - please review and approve

**Comment by sigorbor** [comment]
@ion-elgreco  Integration tests are failing on a clearly unrelated issue.

**Review by ion-elgreco — APPROVED** [review]

**Comment by sigorbor** [comment]
@ion-elgreco @rtyler guys, can we proceed to merging the PR? It is approved and all the checks passed

**Comment by sigorbor** [comment]
@ion-elgreco this PR is approved, can it please be merged? BTW, are there any plans to release a new delta-rs Rust version soon? Any ETA? Would be great if it can happen soon, and include the current PR - we have customers waiting for this fix...

**Comment by ion-elgreco** [comment]
@sigorbor I don't know when the next rust release will be planned, we are waiting for the arrow log functionality to be added and some other things.

**Comment by sigorbor** [comment]
thanks @ion-elgreco 

"Integration tests" fail on apparently unrelated issue.. Could you please merge this PR?

**Comment by ion-elgreco** [comment]
@sigorbor merged it

**Pull request merged**
