### PR TITLE
docs: update changelog for Rust 0.8.0 release

### LINKED ISSUE #1184: Release delta-rs `0.8.0` (next release after `0.7.0`)
Follow on from #1035:
- Planned Release and Publish to crates.io: 2023-03-09

Items:

- [ ] PR to update version and CHANGELOG:
- [ ] Update version to `XXXX` and add changelog
- [ ] Release candidate created:
- [ ] Release to crates.io:

See full list here:
https://github.com/delta-io/delta-rs/compare/rust-v0.7.0...main
cc @houqp @wjones127 @fvaleye @rtyler @roeap @xianwill @mosyp

### PR DESCRIPTION
**Pull request by iajoiner**
# Description
The description of the main changes of your pull request
Update changelog for Rust 0.8.0 release
# Related Issue(s)

Closes #1184.
# Documentation

### CODE REVIEW

**Review by wjones127 — COMMENTED** [review]
This looks good. Should we also update the versions in Cargo.toml in this PR?

**Comment by iajoiner** [comment]
@wjones127 Sure!

**Comment by iajoiner** [comment]
@wjones127 Done haha.

**Review by wjones127 — APPROVED** [review]
Looks good. Thank you!

**Pull request merged**
