### PR TITLE
Fix to support UTC timezone

### PR DESCRIPTION
**Pull request by andrei-ionescu**
# Description

Adds support for UTC timezone.

# Related Issue(s)

- relates to #1019 

# Documentation

### CODE REVIEW

**Comment by fvaleye** [comment]
Thanks for your PR @andrei-ionescu 👍 

Could you please add a unit-test to better describe the issue fixed?

**Comment by andrei-ionescu** [comment]
@fvaleye I added a few tests on the timestamp date type, both ways. I did not add negative tests for other timezones as we may want to support all timezones. I'm not sure why some of the checks do fail. It shows linting errors on files I did not touch at all. Is this a know issue?

**Review by wjones127 — APPROVED** [review]
This looks good to me. Thank you for adding tests! :)

**Review by fvaleye — APPROVED** [review]
Thanks for the tests @andrei-ionescu 👍

**Pull request merged**
