### PR TITLE
Bump version of the Python binding to 0.6.0

### PR DESCRIPTION
**Pull request by fvaleye**
# Description
- Prepare the version [0.6.0](https://github.com/delta-io/delta-rs/releases/tag/untagged-3b7e7d8aa27e35a0a550) of the Python binding
- Bump maturin to version `0.13.2`

### CODE REVIEW

**Comment by roeap** [comment]
thanks for taking care of this! Since this is the opportunity for breaking changes, I am hoping, that we can try and get #761 in and also make a pass through the documentation. At the very least the azure path need some updating.

**Comment by fvaleye** [comment]
Yes, I noticed your ongoing work and we could wait until it's done to release this version!

**Comment by roeap** [comment]
Just for reference some thing we might want to include in this release.

- dependency cleanup #768
- bump pyo3 #757

**Comment by djouallah** [comment]
if i may, can you just guys just release the master branch, so we can test it.

**Comment by houqp** [comment]
@djouallah you should be able to build off master branch yourself, the build process is very straightforward once you have rust toolchain installed.

**Comment by djouallah** [comment]
@houqp I am not a dev, I don't know even what is rust, I know only a bit of sql and python script :)

**Comment by fvaleye** [comment]
@houqp @wjones127 @roeap is it OK for you to wait to merge this [PR](https://github.com/delta-io/delta-rs/pull/774) and then release the new version?

We could fix this issue (https://github.com/delta-io/delta-rs/issues/757) after having pyo3 version `0.17` used in our dependencies!

**Review by wjones127 — APPROVED** [review]

**Review by roeap — APPROVED** [review]

**Comment by fvaleye** [comment]
All right! Thanks @wjones127 @roeap, let's do this!

**Pull request merged**
