### PR TITLE
feat(rust, python): add HDFS support via hdfs-native package

### LINKED ISSUE #2611: Support HDFS via hdfs-native package
# Description
[hdfs-native](https://github.com/Kimahriman/hdfs-native) is a Rust package I made that implements an HDFS client in pure* Rust. This can be used to add HDFS support to delta-rs without any Java or JVM dependencies.

*Kerberos support uses dynamic loading of `libgssapi_krb5` via `libloading`

**Use Case**
Using delta-rs with HDFS without requiring Java

**Related Issue(s)**

### PR DESCRIPTION
**Pull request by Kimahriman**
# Description
Add support for HDFS using [hdfs-native](https://github.com/Kimahriman/hdfs-native), a pure* Rust client for interacting with HDFS. Creates a new `hdfs` sub-crate, adds it as a feature to `deltalake` meta crate, and includes it in Python wheels by default. There is a Rust integration test that requires Hadoop and Java to be installed, and makes use of a small Maven program I ship under the `integration-test` feature flag to run a MiniDFS server.

*Dynamically loads `libgssapi_krb5` using `libloading` for Kerberos support

# Related Issue(s)

Resolves #2611 

# Documentation

### CODE REVIEW

**Comment by ion-elgreco** [comment]
@Kimahriman LGTM! Can you please also add some docs on the integration in the .MD files and if possible links some docs of the possible configs that can be set

@rtyler can you also go over it?

**Comment by Kimahriman** [comment]
> @Kimahriman LGTM! Can you please also add some docs on the integration in the .MD files and if possible links some docs of the possible configs that can be set

Yeah I agree there should be some, but I didn't see anything for other storage backends so I wasn't sure where to add it. Any recommendation? A new page under `integrations/`?

**Comment by ion-elgreco** [comment]
> > @Kimahriman LGTM! Can you please also add some docs on the integration in the .MD files and if possible links some docs of the possible configs that can be set
> 
> Yeah I agree there should be some, but I didn't see anything for other storage backends so I wasn't sure where to add it. Any recommendation? A new page under `integrations/`?
> 

Yeah under integrations makes sense, perhaps called object storage and then a page for hdfs there 

@avriiil any inputs on this? Having some small explanation per object store for S3, adls, gcs and mounted storage would make sense, do you want to help on this?

**Comment by Kimahriman** [comment]
> Yeah under integrations makes sense, perhaps called object storage and then a page for hdfs there

I added a page. I couldn't get the docs to build locally to verify things though. Just kept getting
```
griffe.exceptions.AliasResolutionError: Could not resolve alias deltalake._internal.DeltaError pointing at _internal.DeltaError (in python/deltalake/_internal.abi3.so:None)
```

**Comment by ion-elgreco** [comment]
> > Yeah under integrations makes sense, perhaps called object storage and then a page for hdfs there
> 
> I added a page. I couldn't get the docs to build locally to verify things though. Just kept getting
> ```
> griffe.exceptions.AliasResolutionError: Could not resolve alias deltalake._internal.DeltaError pointing at _internal.DeltaError (in python/deltalake/_internal.abi3.so:None)
> ```
> 

Yeah there is something broken with the docs for some time now

**Review by ion-elgreco — APPROVED** [review]
Thanks for adding this!

**Comment by avriiil** [comment]
Late to the party, I was OOO for a couple of days.

Happy to take a look at creating some more docs if that still makes sense
@ion-elgreco?

~ ~ ~
*Avril Aysha*
DevRel & Content
+351 963681498

**Comment by ion-elgreco** [comment]
@avriiil yeah some docs for each object store would be great 😃

**Comment by avriiil** [comment]
sounds good, adding this to my list for next week @ion-elgreco

**Pull request merged**
