### PR TITLE
docs: add alterer

### PR DESCRIPTION
**Pull request by ion-elgreco**
Again, forgot some docs, and added missing descriptions

### CODE REVIEW

**Comment by MrPowers** [comment]
@ion-elgreco - how will the end user access this functionality?  Like `dt.alter....`?

**Comment by ion-elgreco** [comment]
@MrPowers yeah, `dt.alter.add_constraint()`, and in the future other methods like dt.alter.add_column etc.

**Comment by MrPowers** [comment]
K, so users won't have to access `TableAlterer` directly, perfect!

**Review by MrPowers — APPROVED** [review]
LGTM!

**Pull request merged**
