### PR TITLE
docs: update python docs link in readme.md

### LINKED ISSUE #1898: The Python Docs link in README.MD points to old docs
# Environment

**Delta-rs version**:

**Binding**: 

**Environment**:
- **Cloud provider**:
- **OS**:
- **Other**:

***
# Bug

**What happened**:

The Python Docs link in README.MD points to old docs

**What you expected to happen**:
That it links to the New docs
**How to reproduce it**:

**More details**:

### PR DESCRIPTION
**Pull request by thomasfrederikhoeck**
# Description
Update python docs link in README.md to new website

# Related Issue(s)
closes #1898 

# Documentation

### CODE REVIEW

**Comment by thomasfrederikhoeck** [comment]
@roeap Approve of micro change? :-)

**Comment by roeap** [comment]
@thomasfrederikhoeck thanks for fixing this. do you mind fixing the link in the table below was well?

**Review by MrPowers — APPROVED** [review]

**Comment by MrPowers** [comment]
LGTM 👍

**Comment by thomasfrederikhoeck** [comment]
> @thomasfrederikhoeck thanks for fixing this. do you mind fixing the link in the table below was well?

Done @roeap  :-)

**Review by roeap — APPROVED** [review]
Thanks again!

**Pull request merged**
