### PR TITLE
feat(python): release GIL in the write_deltalake function

### LINKED ISSUE #2234: Release GIL in deltalake.write_deltalake
I'm running `deltalake.write_deltalake` many times in parallel and noticing that my Python process is freezing up a bit.  I suspect that this function has a long period where it doesn't release the GIL.  Is this true?  

If so, I suspect that it's likely accidental, and could be easily changed.  I'm not familiar with the rust-Python tooling, but most Python binding systems make this pretty easy.

### PR DESCRIPTION
**Pull request by franz101**
# Description
Release GIL in deltalake.write_deltalake by wrapping it in py.allow_threads
# Related Issue(s)
- closes #2234
# Documentation

### CODE REVIEW

**Comment by mrocklin** [comment]
Cool!  If this works well I suspect that the same pattern would also be useful on other common operations (compact, vacuum, etc..)

**Comment by ion-elgreco** [comment]
@franz101 you're missing `py: Python,` as the first variable of the function defintion

**Comment by franz101** [comment]
> Cool! If this works well I suspect that the same pattern would also be useful on other common operations (compact, vacuum, etc..)
Essentially all methods [here](https://delta-io.github.io/delta-rs/api/delta_table/#deltalake.DeltaTable.update):
- `create`
- `delete`
- `optimize`
- `vacuum`
- ...

**Comment by mrocklin** [comment]
Looks good to me :)

**Pull request merged**
