### PR TITLE
Fix generated parquet filename

### PR DESCRIPTION
**Pull request by viirya**
# Description

The current parquet filename is appended with partition values, e.g. `part-0000-xxxx-c000.snappy.parquet/part1=value1/part2=value2`. Seems it doesn't follow existing conventions as `part1=value1/part2=value2/...` .

# Related Issue(s)

# Documentation

### CODE REVIEW

**Review by houqp — APPROVED** [review]
Good catch, thanks for adding tests as well!

**Comment by houqp** [comment]
@viirya looks like there are minor formatting errors: https://github.com/delta-io/delta-rs/pull/291/checks?check_run_id=2815237004, could you format the code with https://github.com/rust-lang/rustfmt?

**Comment by viirya** [comment]
Thanks @houqp. Fixed the format.

**Review by houqp — APPROVED** [review]

**Comment by viirya** [comment]
Oh, seems the test fails on windows because of path separator. I will fix it.

**Comment by houqp** [comment]
Turns out our auto merge setting allows merge with broken windows CI. can't tell if that's a feature or a bug :)

**Pull request merged**
