### PR TITLE
chore: set max_retries in CommitProperties

### PR DESCRIPTION
**Pull request by helanto**
# Description
Adds a `with_max_retries` in `CommitProperties`. Allow for clients to control the maximum number of times a commit will be retried before failing.

# Related Issue(s)

# Documentation

### CODE REVIEW

**Comment by ion-elgreco** [comment]
This needs to be exposed for python users as well

**Review by rtyler — DISMISSED** [review]

**Comment by helanto** [comment]
> This needs to be exposed for python users as well

Not super familiar with how Python binding works. Made an attempt to expose the `max_commit_retries` in Python API. Let me know what you think.

**Comment by ion-elgreco** [comment]
@helanto Hmm perhaps we can introduce a CommitProperties class, where you have custom_metadata and commit_retries as variables, this would be a breaking change, so we need to warn users that custom_metadata should be passed into CommitProperties

**Comment by helanto** [comment]
> @helanto Hmm perhaps we can introduce a CommitProperties class, where you have custom_metadata and commit_retries as variables, this would be a breaking change, so we need to warn users that custom_metadata should be passed into CommitProperties

I believe I made the change. How do we warn users ?

**Comment by ion-elgreco** [comment]
> > @helanto Hmm perhaps we can introduce a CommitProperties class, where you have custom_metadata and commit_retries as variables, this would be a breaking change, so we need to warn users that custom_metadata should be passed into CommitProperties
> 
> I believe I made the change. How do we warn users @ion-elgreco ?

You can check in other places of the code base, where we show a warn when a parameter is passed that is deprecated

**Comment by helanto** [comment]
> You can check in other places of the code base, where we show a warn when a parameter is passed that is deprecated

This means that we keep both parameters around. Do you have something in mind along the following lines?
```python
def operation(
    ....,
    custom_metadata: Optional[Dict[str, str]] = None,  # We keep this around for compatibility reasons.
    commit_properties: OptionalCommit[Properties] = None,
):
    if custom_metadata is not None:
        warn("Please provide custom_metadata as part of commit_properties").
    ...
```

**Comment by ion-elgreco** [comment]
> > You can check in other places of the code base, where we show a warn when a parameter is passed that is deprecated
> 
> This means that we keep both parameters around. Do you have something in mind along the following lines?
> ```python
> def operation(
>     ....,
>     custom_metadata: Optional[Dict[str, str]] = None,  # We keep this around for compatibility reasons.
>     commit_properties: OptionalCommit[Properties] = None,
> ):
>     if custom_metadata is not None:
>         warn("Please provide custom_metadata as part of commit_properties").
>     ...
> ```

Yess, and then custom_metadata can be dropped in later versions

**Comment by ion-elgreco** [comment]
@helanto do you have time to make that change? Because then we can merge :  )

**Comment by helanto** [comment]
> @helanto do you have time to make that change? Because then we can merge : )

Yes I will work on it today!

**Comment by helanto** [comment]
> > @helanto do you have time to make that change? Because then we can merge : )
> 
> Yes I will work on it today!

I believe I made the changes if you can take a look @ion-elgreco

**Comment by ion-elgreco** [comment]
@helanto just one more thing, commit_metadata in the pyo3 functions can be removed, and in Python if custom metadata is still passed, you can wrap it into CommitPropeti e

**Comment by helanto** [comment]
> @helanto just one more thing, commit_metadata in the pyo3 functions can be removed, and in Python if custom metadata is still passed, you can wrap it into CommitPropeti e

I look at pyo3 function definitions and they don't have any `commit_metadata` argument ? Do you mean `custom_metadata` ? The pyo3 functions look like the following:
```rust
#[pyo3(signature = ...)]
pub fn some_function(
        ...,
        custom_metadata: Option<HashMap<String, String>>,
        max_commit_retries: Option<usize>,
)
```

I can create a pyo3 class that wraps `custom_metadata` and `max_commit_retries`, similar to `PyPostCommitHookProperties` [here](https://github.com/delta-io/delta-rs/blob/main/python/src/lib.rs#L1588). At the moment the `CommitProperties` only exist as a publicly facing Python class, it's not a pyo3 class. @ion-elgreco

**Comment by ion-elgreco** [comment]
Yeah I meant custom_metadata

**Comment by helanto** [comment]
> Yeah I meant custom_metadata. We need a rust struct which has a derive indeed

Now it should be good! Let me know what you think @ion-elgreco

**Review by ion-elgreco — APPROVED** [review]
Thankss!!

**Review by ion-elgreco — APPROVED** [review]

**Pull request merged**
