### PR TITLE
docs: add logo, dark mode, boost search

### PR DESCRIPTION
**Pull request by ion-elgreco**
- Adds transparent logo (we need a higher quality one), I've pinged @fvaleye on Slack to check whether he has one.
- Add dark mode toggle
- Boost some search results since it was prioritizing the guides over the API reference

### CODE REVIEW

**Comment by roeap** [comment]
if the logo is transparent, should we use it in the README as well?

w.r.t. boosting API reference, depending on the audience, the examples might be more helpful? maybe @MrPowers has an opinion?

**Comment by MrPowers** [comment]
LGTM, but not sure about the search boosting...  My guess is that we want the usage/integration pages ranked above the API docs (and the usage pages linking to the API docs).  Open to thoughts.  Normally I don't think API docs give the best SEO experience.

**Comment by roeap** [comment]
@dennyglee made me aware of the [assets](https://github.com/delta-io/delta-docs/tree/main/static/images/logos/_icons/delta-rust) available in the delta-docs repo. Maybe we should use these? There are high quality PNGs as well as SVG versions available.

**Comment by ion-elgreco** [comment]
Awesome @roeap @dennyglee! That was what I was looking for :D

**Pull request merged**
