### PR TITLE
feat: add metadata for operations::write::WriteBuilder

### PR DESCRIPTION
**Pull request by abhimanyusinghgaur**
# Description
This PR simply provides a way to add commit metadata during `DeltaOps::write()` operation similar to `DeltaOps::update()`.

# Related Issue(s)
None

# Documentation
None

### CODE REVIEW

**Review by rtyler — APPROVED** [review]
I would love to see a test included but this is still an improvement

**Comment by abhimanyusinghgaur** [comment]
> I would love to see a test included but this is still an improvement 

Thanks for the review. I'm not much aware about the test setup in the repo. Could you please let me know which place I can add the test?

**Comment by abhimanyusinghgaur** [comment]
@rtyler I have added tests. Please have a look and let me know if there's anything else required.

Thanks

**Review by roeap — APPROVED** [review]
Thanks for adding this!

**Pull request merged**
