### PR TITLE
WIP: Record Batch support for delta log stats_parsed (#435)

### PR DESCRIPTION
**Pull request by mgill25**
- Initial attempt at creating record batches out of stats_parsed from the delta log for `Add` actions.
- A new representation for the stats via `StatRecordBatch`
- Currently only supports creation of batches for columns that have integer types. Hard-coded `i64`s for now. Of course, this needs to be extended to provide support for more types.
- Added an associated test case.

The basic idea is to simply provide the Arrow schema for the columns for which we want to create the batches. I've left the selection of columns as an argument - I can see cases where it might not make sense to keep statistics for _all columns_.

I only parse `minValues`, `maxValues` and `numRecords` for now. `nullCounts` need to be added.

Additionally, `StatRecordBatch` is _not_ yet embedded into the primary `Add` struct yet. I ran into some issues there and plan to figure that out in the coming days/weeks.

First PR. I'm sure there's plenty of things that need to be improved here. Feedback is very much appreciated! :)

### CODE REVIEW

**Comment by houqp** [comment]
Thanks @mgill25 for taking on this initiative! I think to fully leverage the columnar design, we can't store the stats in the action struct itself. We will need to store them in a level of abstraction that's higher than Action. I am going to take another look at the design to write up some of my thoughts as a follow up comment.

**Comment by mosyp** [comment]
@mgill25 Hi, great PR. I wonder whether you're planning on finish that. Also alternatively @houqp, we could merge it to the new feature branch instead and work on it collectively. 

The mem issue has become the concern for us so we thinking either we can benefit from this feature or not storing struct actions in memory at all (for kafka-delta-ingest we don't need them)

**Comment by manishgill-tomtom** [comment]
Re: the design ideas, @houqp I'm not well versed in Arrow enough to make the best design decision, so perhaps `Vec<Option<T>>` is the short term solution we take for now? I will try to make an update to the PR this week.

**Comment by dispanser** [comment]
> The mem issue has become the concern for us so we thinking either we can benefit from this feature or not storing struct actions in memory at all (for kafka-delta-ingest we don't need them)

If you don't need the stats for the use case, not storing them at all is may be the best (and cheapest option). An alternative "workaround" for memory consumption problems that I can see would be to have configurable whilelist of columns for which the stats are useful, and discard the rest. For our use case, most of these column stats are useless (e.g., UUIDs min / max stats tend to not have any filtering capability). 

There's a possibility in delta itself to control this to some extend already on the write, but it involves reordering columns (and assumes that the table consumer can convince the table producer to perform that change).

**Comment by houqp** [comment]
Sorry for the late response, last 2 weeks have been crazy for me, so I am still catching up on all the great discussions :)

> Re: the design ideas, @houqp I'm not well versed in Arrow enough to make the best design decision, so perhaps Vec<Option<T>> is the short term solution we take for now? I will try to make an update to the PR this week.

This sounds good to me :+1: 

> If you don't need the stats for the use case, not storing them at all is may be the best (and cheapest option). An alternative "workaround" for memory consumption problems that I can see would be to have configurable whilelist of columns for which the stats are useful, and discard the rest. For our use case, most of these column stats are useless (e.g., UUIDs min / max stats tend to not have any filtering capability).

I think supporting projection based stats loading could be an interesting and useful feature to add :+1: 

These optimization probably wont' help with kafka-delta-ingest though since it doesn't know if downstream consumer of the table will need these stats or not.

**Comment by mgill25** [comment]
Apologies for zero activity on this for the last 2 months. 

I think for now I don't have the bandwidth to work on this, so if anyone wants to pick this up, please feel free to.

**Comment by roeap** [comment]
superseded by #2037

**Pull request closed without merging**
