### PR TITLE
fix: don't re-encode paths

### LINKED ISSUE #1079: Paths in add actions aren't always percent-decoded
# Environment

**Delta-rs version**:

**Binding**: 

**Environment**:
- **Cloud provider**:
- **OS**:
- **Other**:

***
# Bug

Our methods `get_files_by_partition()` and `get_files_iter()` take the raw paths, without decoding the percent-encoded characters. I wonder if we can do that decoding when deserializing the JSON actions? Also we should see whether this is necessary for Parquet checkpoints.

### LINKED ISSUE #1228: Error reading partitioned table with slash in partition key
# Environment

**Delta-rs version**: 0.8.1

**Binding**: python

**Environment**:
- Azure and locally

***
# Bug

**What happened**:
I'm saving a partitioned table in Databricks (DBR 12.1) into Azure Data Lake Storage V2 which is partitioned on a string column containing slashes. When trying to read the table using deltalake from my local pc I get an error saying there is 'No body' in the parquet file.

```
Traceback (most recent call last):
  File "[..]/delta_connect.py", line 32, in <module>
    table = dt.to_pandas(
  File "[..]/python3.10/site-packages/deltalake/table.py", line 418, in to_pandas
    return self.to_pyarrow_table(
  File "[..]/python3.10/site-packages/deltalake/table.py", line 400, in to_pyarrow_table
    return self.to_pyarrow_dataset(
  File "pyarrow/_dataset.pyx", line 369, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 2818, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/_fs.pyx", line 1551, in pyarrow._fs._cb_open_input_file
  File "[..]/python3.10/site-packages/deltalake/fs.py", line 22, in open_input_file
    return pa.PythonFile(DeltaFileSystemHandler.open_input_file(self, path))
deltalake.PyDeltaTableError: Object at location partition_table_test/value=you%25252Fthere/part-00007-adfd81b1-1bff-4431-83c2-948e2274a892.c000.snappy.parquet not found: response error "No Body", after 0 retries: HTTP status client error (404 Not Found) for url [..]
```
If I query for a key without a slash it returns the data without issue.

**What you expected to happen**:
Succesfully read the data

**How to reproduce it**:
In Databricks saving to ADLS2:

```python
df = spark.createDataFrame([
    (0, "hej"),
    (1, "you/there"),
    (2, "the two of us"),
], schema="id int, value string")
df.write.partitionBy("value").saveAsTable("mytable")
```

Locally running in python (3.10) gives the above error:

```python
from deltalake import DeltaTable

container_name = "my_container"
storage_account_name = "my_sa"
table_name = "my_table"
sas_token = "my_sas_token"

abfs_path = (
    f"abfs://{container_name}@{storage_account_name}.dfs.core.windows.net/{table_name}/"
)

dt = DeltaTable(
    abfs_path,
    storage_options={
        "sas_key": sas_token,
    },
)

table = dt.to_pandas(
    partitions=[("value", "=", "you/there")],
)
```

Using the other value "hej" works fine:
```python

table = dt.to_pandas(
    partitions=[("value", "=", "hej")],
)
```
returns:

```
    id value
0   0   hej
```
**More details**:

### LINKED ISSUE #1393: Cannot read partitions with special characters (including space) with pyarrow >= 11
# Environment

**Delta-rs version**: 
**Binding**: Python
**Environment**: Python==3.10, deltalake==0.9.0, pyarrow==11.0.0
- **Cloud provider**: N/A
- **OS**: Ubuntu 22.04
- **Other**:

***
# Bug

**What happened**: 

If the values of a column contain special characters (including space) the writer encodes them when using the column as a partition. If you then try to read the table with the same column as a partition, it finds nothing.

This bug happens if the pyarrow version is >= 11. It works with pyarrow 10.0.1 (special characters not encoded).

**What you expected to happen**: Partition of a column with special characters correctly read even if they are encoded.

**How to reproduce it**:

```python
import deltalake as dl
import pyarrow as pa

n_legs = pa.array([2, 4, 5, 100])
animals = pa.array(["Flamingo", "Horse", "Brittle Stars", "Centipede"])
names = ["n_legs", "animals"]

pa_table = pa.Table.from_arrays([n_legs, animals], names=names)

dt_table_uri = "tmp"
dl.write_deltalake(dt_table_uri, pa_table, partition_by=["animals"], mode="overwrite")

dt_table = dl.DeltaTable(dt_table_uri)
dt_table.to_pyarrow_table(partitions=[("animals", "=", "Brittle Stars")]).num_rows
```

It `num_rows` returns 0, 1 is expected.

**More details**:

The content of the `/tmp` folder is

```bash
$ ls -1 tmp/
'animals=Brittle%2520Stars'
'animals=Centipede'
'animals=Flamingo'
'animals=Horse'
_delta_log
```

Note: even if i try with `Brittle%2520Stars` as partition value the `num_rows` returns 0.

With pyarrow 10.0.1 the same script gives `num_rows` equal to 1 and the folder is

```bash
$ ls -1 tmp/
'animals=Brittle Stars'
'animals=Centipede'
'animals=Flamingo'
'animals=Horse'
_delta_log
```

as expected.

### LINKED ISSUE #1446: Partition values that have been url encoded cannot be read when using deltalake
# Environment

pyarrow             11.0.0
deltalake           0.9.0

**Binding**: Python

**Environment**:
- **Cloud provider**: AWS
- **OS**: Linux
- **Other**:

***
# Bug

**What happened**:

Receiving an error when attempting to read partition values that have a colon

**What you expected to happen**:

I would expect to be able to read these partitions like I can using pyspark

**How to reproduce it**:

Create a delta table partitioned by timestamp using PySpark. Example partition value: 2023-06-07 13:00:00. When data is loaded to the partition it creates a folder such as this:

`'load_ts=2023-06-07 13%3A00%3A00'`

Then when running the below code:

```python
from deltalake import DeltaTable
dt = DeltaTable('/spark-warehouse/mock_table_partitioned')
dt.to_pandas()
```

I encounter the following error. Notice that in the error message it has url encoded the % resulting in %25253A instead of %3A:

```python
File /usr/local/lib/python3.9/dist-packages/deltalake/table.py:442, in DeltaTable.to_pandas(self, partitions, columns, filesystem)
    428 def to_pandas(
    429     self,
    430     partitions: Optional[List[Tuple[str, str, Any]]] = None,
    431     columns: Optional[List[str]] = None,
    432     filesystem: Optional[Union[str, pa_fs.FileSystem]] = None,
    433 ) -> "pandas.DataFrame":
    434     """
    435     Build a pandas dataframe using data from the DeltaTable.
    436
   (...)
    440     :return: a pandas dataframe
    441     """
--> 442     return self.to_pyarrow_table(
    443         partitions=partitions, columns=columns, filesystem=filesystem
    444     ).to_pandas()

File /usr/local/lib/python3.9/dist-packages/deltalake/table.py:424, in DeltaTable.to_pyarrow_table(self, partitions, columns, filesystem)
    410 def to_pyarrow_table(
    411     self,
    412     partitions: Optional[List[Tuple[str, str, Any]]] = None,
    413     columns: Optional[List[str]] = None,
    414     filesystem: Optional[Union[str, pa_fs.FileSystem]] = None,
    415 ) -> pyarrow.Table:
    416     """
    417     Build a PyArrow Table using data from the DeltaTable.
    418
   (...)
    422     :return: the PyArrow table
    423     """
--> 424     return self.to_pyarrow_dataset(
    425         partitions=partitions, filesystem=filesystem
    426     ).to_table(columns=columns)

File /usr/local/lib/python3.9/dist-packages/pyarrow/_dataset.pyx:369, in pyarrow._dataset.Dataset.to_table()

File /usr/local/lib/python3.9/dist-packages/pyarrow/_dataset.pyx:2818, in pyarrow._dataset.Scanner.to_table()

File /usr/local/lib/python3.9/dist-packages/pyarrow/error.pxi:144, in pyarrow.lib.pyarrow_internal_check_status()

File /usr/local/lib/python3.9/dist-packages/pyarrow/_fs.pyx:1551, in pyarrow._fs._cb_open_input_file()

File /usr/local/lib/python3.9/dist-packages/deltalake/fs.py:22, in DeltaStorageHandler.open_input_file(self, path)
     15 def open_input_file(self, path: str) -> pa.PythonFile:
     16     """
     17     Open an input file for random access reading.
     18
     19     :param source: The source to open for reading.
     20     :return:  NativeFile
     21     """
---> 22     return pa.PythonFile(DeltaFileSystemHandler.open_input_file(self, path))

PyDeltaTableError: Object at location /spark-warehouse/mock_table_partitioned/load_dt=2023-05-12 00%25253A00%25253A00/part-00000-132eef45-d5e6-40e0-be85-383dd7c60b4c.c000.snappy.parquet not found: No such file or directory (os error 2)
```

**More details**:

This is happening when using local storage or aws s3. I also do not encounter this issue if reading these partitions from within pyspark.

### LINKED ISSUE #1533: [Python] Incorrect file URIs when partition values contain escape character
# Environment

**Delta-rs version**: 0.10.0

**Binding**: Python

**Environment**:
- **Cloud provider**:
- **OS**: macOS
- **Other**:

***
# Bug

**What happened**:

When partition values contain an escape character (example: `letter=%2F%2520%25f`), `deltalake` returns incorrect `file_uris` - they seem to have an additional level of urlencoding.

**What you expected to happen**:

`file_uris` to return uris that correspond to actual file names.

**How to reproduce it**:

1. Download data from Delta Acceptance Testing (https://github.com/delta-incubator/dat/)

`wget https://github.com/delta-incubator/dat/releases/download/v0.0.2/deltalake-dat-v0.0.2.tar.gz`

2. Extract the data.
3. Check `file_uris`:

```python
> ipython
In [1]: from deltalake import DeltaTable

In [2]: dt = DeltaTable("out/reader_tests/generated/multi_partitioned/delta")

In [3]: dt.file_uris()
Out[3]:
['/Users/jbennet/src/delta-rs/python/out/reader_tests/generated/multi_partitioned/delta/letter=%252F%252520%2525f/date=1970-01-01/data=hello/part-00000-a29a3f63-5a26-4127-aeff-e6d27c077917.c000.snappy.parquet',
 '/Users/jbennet/src/delta-rs/python/out/reader_tests/generated/multi_partitioned/delta/letter=b/date=1970-01-01/data=%F0%9F%98%88/part-00000-9363b3d0-34b9-4db4-baf6-9b48cf88ae5b.c000.snappy.parquet']
```

The actual paths do not correspond to returned urls:

```
In [4]: ! ls -l /Users/jbennet/src/delta-rs/python/out/reader_tests/generated/multi_partitioned/delta/
total 0
drwxr-xr-x  8 jbennet  staff  256 Jan 24 17:50 _delta_log
drwxr-xr-x  3 jbennet  staff   96 Jan 24 17:50 letter=%2F%2520%25f
drwxr-xr-x  3 jbennet  staff   96 Jan 24 17:50 letter=__HIVE_DEFAULT_PARTITION__
drwxr-xr-x  4 jbennet  staff  128 Jan 24 17:50 letter=a
drwxr-xr-x  4 jbennet  staff  128 Jan 24 17:50 letter=b
```

Actual path: `letter=%2F%2520%25f`
Returned by `delta-rs`: `letter=%252F%252520%2525f`

**More details**:

### PR DESCRIPTION
**Pull request by wjones127**
# Description

In the delta log, paths are percent encoded. We decode them here:

https://github.com/delta-io/delta-rs/blob/787c13a63efa9ada96d303c10c093424215aaa80/rust/src/action/mod.rs#L435-L437

Which is good. But then we've been re-encoding them with `Path::from`. This PR changes to use `Path::parse` when possible instead. Instead of propagating errors, we just fallback to `Path::from` for now. Read more here: https://docs.rs/object_store/0.7.0/object_store/path/struct.Path.html#encode

# Related Issue(s)

* closes #1533
* closes #1446 
* closes #1079
* closes #1393
* closes #1228

# Documentation

### CODE REVIEW

**Review by rtyler — DISMISSED** [review]

**Comment by mahinshaw** [comment]
This also resolves the issue in #1228 based on my testing.

**Review by rtyler — APPROVED** [review]

**Comment by ABChristian** [comment]
Testing with 0.10.2 i could still reproduce the issue #1391 
Writing to a path containing spaces (due to a parent folder, i.e. "./deltalake/data") works correctly as expected, using the same location for reading will yield an error:

`FileNotFoundError: Object at location C:\Users\Me\FirstPart%20-%20SecondPart\PyDev\deltalake\data\0-f8ffed19-9033-4ba6-8cbe-043295af18d1-0.parquet not found`

**Comment by djouallah** [comment]
yep, same problem here

**Comment by wjones127** [comment]
@ABChristian Thanks for testing. I'll take a look at that soon.

**Comment by Phil-T1** [comment]
Using 0.10.2, I'm having this same issue where Windows paths cannot be decoded due to their spaceyness.

Writing only succeeds where paths which have no space characters. :(

**Comment by JvdH-NL** [comment]
Using 0.16.4 I am having same issue. Running Python code from a path that contains spaces gives me 'object at location <FILL PATH WITH SPACES that have been replaced with %20 .... parquet file> not found ....
I have some sample data, using code, fails on last statement. And path is on corporate OneDrive containing spaces.
delta_table_path = 'deltaTable/'
dt = DeltaTable(delta_table_path)
# Read Data from Delta table
dt.to_pandas()

**Comment by JvdH-NL** [comment]
Quickstart on Homepage results in error in reading (writing part goes ok), same issue as my previous post.

**Pull request merged**
