### PR TITLE
Try to fix flaky rename under Windows

### PR DESCRIPTION
**Pull request by viirya**
# Description

Seems async rename under Windows is flaky due to no native rename if not exists support.
Use a shared lock to prevent threads renaming at the same time.

# Related Issue(s)

# Documentation

### CODE REVIEW

**Comment by houqp** [comment]
Thanks @viirya , if this doesn't work we can also just replace the windows rename code with `unimplemented` since the current rename is not atomic anyway, so shouldn't be used in any serious context.

**Comment by viirya** [comment]
It passed the windows test. Let me trigger it more times to verify.

**Comment by viirya** [comment]
It also passed windows test in 2nd and third time. Looks okay? The failure of building Sphinx document for python_build looks unrelated.

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
Thanks @viirya ! yeah, the python build is something different.

**Comment by viirya** [comment]
Thank you @houqp !

**Pull request merged**
