### PR TITLE
Update versions to 0.6.0 and update changelog

### LINKED ISSUE #971: Release delta-rs `0.6.0` (next release after `0.5.0`)
Here is our first monthly release:
- Planned Release and Publish to crates.io: 2022-12-16

CI and release-related enhancements we want to add in this or the next release:
- [x] #1000 
- [ ] #996 
- [ ] #984
- [ ] #1026

Bugs we want to fix in this or the next release:
- [ ]  #677 / #925 / #985
- [ ] #973 / #1002
- [ ] #1025

Items:

- [x] PR to update version and CHANGELOG (#1023):
- [ ] Update version to 0.6.0 and add changelog
- [ ] Release candidate created:
- [ ] Release candidate approved:
- [ ] Release to crates.io:

See full list here:
https://github.com/delta-io/delta-rs/compare/rust-v0.5.0...main
cc @houqp @wjones127 @fvaleye @rtyler @roeap @xianwill @mosyp

### PR DESCRIPTION
**Pull request by iajoiner**
# Description
The description of the main changes of your pull request

# Related Issue(s)

Closes #971 
# Documentation

### CODE REVIEW

**Review by andrei-ionescu — APPROVED** [review]
🚀

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
Thank you @iajoiner !

**Review by roeap — APPROVED** [review]
Thanks for doing this!

**Comment by iajoiner** [comment]
Please merge this. Really thanks!

**Pull request merged**
