### PR TITLE
fix: introduce support for Microsoft OneLake

### PR DESCRIPTION
**Pull request by rtyler**
# Description

This is a rebase and update of #1564 which already has some robust discussion. 

# Related Issue(s)

Closes #1564

### CODE REVIEW

**Review by wjones127 — APPROVED** [review]
Seems okay. Would ideally like the tests run in CI and use the full `test_object_store` suite.

**Comment by rtyler** [comment]
@wjones127 Me too, but the only way I think we do that is if I set up an Azure account and plonk some secrets into CI like I have done in the past for S3.


I'll think about it :laughing:

**Comment by vmuddassir-msft** [comment]
@rtyler - Thanks for getting this merged , since a dynamically generated jwt token is used for now it will might not be possible to store this Github secrets. Can you please let me know the release date for deltalake package

https://crates.io/crates/deltalake/versions - The last update seems to have been published on 2 weeks ago

**Comment by rtyler** [comment]
@vmuddassir-msft please watch the repository's releases 
image

**Pull request merged**
