### PR TITLE
docs: updating docs for MinIO and Docker, with working conditional put support

### LINKED ISSUE #2894: Cannot write to Minio with deltalake.write_deltalake or Polars
# Environment

**Delta-rs version**: 0.20.0

**Binding**:  Python

**Environment**:
- **Cloud provider**: Local (Minio, via Docker)
- **OS**: Mac OS 12.5, M2 CPU
- **Other**:

***
# Bug

**What happened**:
Running Minio locally via docker-compose (.yml spec below), attempted to write a 20-row Pyarrow table via the write_deltalake function, and got the opaque error message:

Generic S3 error: Error after 0 retries in 71.583µs, max_retries:10, retry_timeout:180s, source:builder error for url (http://localhost:9000/test-bucket/test_delta_table/_delta_log/_last_checkpoint) 

Attempted to write a 20-row pandas dataframe via the polars write_delta function as well, and got the exact same error:

Generic S3 error: Error after 0 retries in 71.583µs, max_retries:10, retry_timeout:180s, source:builder error for url (http://localhost:9000/test-bucket/test_delta_table/_delta_log/_last_checkpoint)

**What you expected to happen**:
I expected to be able to write tables out to Minio via S3.  I have tested that I can write to Minio just fine with boto3.
I'm happy to do more footwork chasing this down, turning up logging, or reproducing it deeper in the stack if someone can point me in the right direction!

**How to reproduce it**:
```
import boto3
import random
import string
import pyarrow as pa
from deltalake import write_deltalake, DeltaTable

# Configuration
endpoint_url = 'http://localhost:9000'
access_key = 'minioadmin'
secret_key = 'minioadmin'
bucket_name = 'test-bucket'
table_name = 'test_delta_table'
num_rows = 10

# Generate random string function
def generate_random_string(length=5):
    return ''.join(random.choices(string.ascii_lowercase, k=length))

# Generate data
keys = [generate_random_string() for _ in range(num_rows)]
values = [generate_random_string() for _ in range(num_rows)]

# Create PyArrow table
table = pa.table([keys, values], names=['key', 'value'])

table_path = f"s3://{bucket_name}/{table_name}"

print(f"Writing Delta table to: {table_path}")

storage_options = {
    "AWS_ACCESS_KEY_ID": access_key,
    "AWS_SECRET_ACCESS_KEY": secret_key,
    "AWS_ENDPOINT_URL": endpoint_url,
    "AWS_REGION": "us-east-1",
    "AWS_S3_ALLOW_UNSAFE_RENAME": "true"
}

try:
    # Check if MinIO is accessible
    s3 = boto3.client('s3', endpoint_url=endpoint_url)
    s3.list_buckets()
    print("Successfully connected to MinIO")

    # Check if the bucket exists
    buckets = s3.list_buckets()['Buckets']
    if not any(bucket['Name'] == bucket_name for bucket in buckets):
        print(f"Bucket {bucket_name} does not exist. Creating it...")
        s3.create_bucket(Bucket=bucket_name)

    # Write to S3
    write_deltalake(
        table_path,
        table,
        mode="overwrite",
        storage_options=storage_options
    )
    print(f"Successfully wrote Delta table to {table_path}")

    # Read and print the table metadata
    dt = DeltaTable(table_path, storage_options=storage_options)
    print(f"Table metadata:\n{dt.metadata()}")
    print(f"Table schema:\n{dt.schema().json()}")
    print(f"Table version: {dt.version()}")

except Exception as e:
    print(f"Error writing Delta table: {e}")
```

**More details**:
docker-compose.yml:
```
version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
```

### PR DESCRIPTION
**Pull request by rwhaling**
# Description
Fixes a few typos in cloudflare/minio docs page, adds working docker example and notes on special storage_option flags for http vs https.

# Related Issue(s)
- closes #2894

# Notes
Updated docs to use `"aws_conditional_put":"etag"` due to the issue identified below.

### CODE REVIEW

**Comment by ion-elgreco** [comment]
@rwhaling any errors with conditional put?

**Comment by rwhaling** [comment]
Yep @ion-elgreco, just commented in the issue, but getting `Operation not supported: S3 does not support copy-if-not-exists.`

**Comment by rwhaling** [comment]
@ion-elgreco sure, thank you!

With ```storage_options = {
    "conditional_put": "etag",
    "AWS_ACCESS_KEY_ID": access_key,
    "AWS_SECRET_ACCESS_KEY": secret_key,
    "AWS_ENDPOINT_URL": endpoint_url,
    "AWS_ALLOW_HTTP": "true"
}
```
I get these logs: 
```
[2024-09-22T15:49:35Z DEBUG deltalake_core::table::builder] creating table builder with s3://test-bucket/test_delta_table
[2024-09-22T15:49:35Z DEBUG deltalake_core::table::builder] build_storage() with s3://test-bucket/test_delta_table
[2024-09-22T15:49:35Z DEBUG deltalake_core::table::builder] Loading a logstore based off the location: Url { scheme: "s3", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("test-bucket")), port: None, path: "/test_delta_table", query: None, fragment: None }
[2024-09-22T15:49:35Z DEBUG deltalake_core::logstore] Found a storage provider for s3:// (s3://test-bucket/test_delta_table)
[2024-09-22T15:49:35Z INFO  object_store::aws::builder] Using Static credential provider
[2024-09-22T15:49:35Z DEBUG deltalake_core::logstore] Found a logstore provider for s3://
[2024-09-22T15:49:35Z DEBUG tracing::span] build_profile_provider;
[2024-09-22T15:49:35Z DEBUG aws_sdk_sts::endpoint_lib] loading default partitions
[2024-09-22T15:49:35Z DEBUG hyper_rustls::config] with_native_roots processed 158 valid and 0 invalid certs
[2024-09-22T15:49:35Z INFO  aws_config::meta::region] load_region; provider=EnvironmentVariableRegionProvider { env: Env(Real) }
[2024-09-22T15:49:35Z INFO  aws_config::meta::region] load_region; provider=ProfileFileRegionProvider { provider_config: ProviderConfig { env: Env(Real), fs: Fs(Real), time_source: SharedTimeSource(SystemTimeSource), http_client: None, sleep_impl: Some(SharedAsyncSleep(TokioSleep)), region: None, use_fips: None, use_dual_stack: None, profile_name_override: None } }
[2024-09-22T15:49:35Z DEBUG aws_runtime::fs_util] loaded home directory src="HOME"
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] load_config_file; file=Default(Config)
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] performing home directory substitution home="/Users/richardwhaling" path="~/.aws/config"
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] home directory expanded before="~/.aws/config" after="/Users/richardwhaling/.aws/config"
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] config file not found path=~/.aws/config
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] config file loaded path=Some("/Users/richardwhaling/.aws/config") size=0
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] load_config_file; file=Default(Credentials)
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] performing home directory substitution home="/Users/richardwhaling" path="~/.aws/credentials"
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] home directory expanded before="~/.aws/credentials" after="/Users/richardwhaling/.aws/credentials"
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] config file not found path=~/.aws/credentials
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] config file loaded path=Some("/Users/richardwhaling/.aws/credentials") size=0
[2024-09-22T15:49:35Z DEBUG tracing::span] build_profile_token_provider;
[2024-09-22T15:49:35Z DEBUG aws_runtime::fs_util] loaded home directory src="HOME"
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] load_config_file; file=Default(Config)
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] performing home directory substitution home="/Users/richardwhaling" path="~/.aws/config"
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] home directory expanded before="~/.aws/config" after="/Users/richardwhaling/.aws/config"
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] config file not found path=~/.aws/config
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] config file loaded path=Some("/Users/richardwhaling/.aws/config") size=0
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] load_config_file; file=Default(Credentials)
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] performing home directory substitution home="/Users/richardwhaling" path="~/.aws/credentials"
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] home directory expanded before="~/.aws/credentials" after="/Users/richardwhaling/.aws/credentials"
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] config file not found path=~/.aws/credentials
[2024-09-22T15:49:35Z DEBUG aws_runtime::env_config::source] config file loaded path=Some("/Users/richardwhaling/.aws/credentials") size=0
[2024-09-22T15:49:35Z DEBUG deltalake_aws] S3LogStoreFactory has been asked to create a LogStore without the dynamodb locking provider
[2024-09-22T15:49:35Z DEBUG reqwest::connect] starting new connection: http://localhost:9000/
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::dns] resolving host="localhost"
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::http] connecting to [::1]:9000
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::http] connected to [::1]:9000
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG reqwest::connect] starting new connection: http://localhost:9000/
[2024-09-22T15:49:35Z DEBUG reqwest::connect] starting new connection: http://localhost:9000/
[2024-09-22T15:49:35Z DEBUG reqwest::connect] starting new connection: http://localhost:9000/
[2024-09-22T15:49:35Z DEBUG reqwest::connect] starting new connection: http://localhost:9000/
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::dns] resolving host="localhost"
[2024-09-22T15:49:35Z DEBUG reqwest::connect] starting new connection: http://localhost:9000/
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::dns] resolving host="localhost"
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::dns] resolving host="localhost"
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::dns] resolving host="localhost"
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::dns] resolving host="localhost"
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::http] connecting to [::1]:9000
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::http] connecting to [::1]:9000
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::http] connecting to [::1]:9000
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::http] connected to [::1]:9000
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::http] connected to [::1]:9000
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::http] connected to [::1]:9000
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::http] connecting to [::1]:9000
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::http] connecting to [::1]:9000
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::http] connected to [::1]:9000
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::connect::http] connected to [::1]:9000
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG deltalake_core::kernel::snapshot::log_segment] try_new_slice: start_version: 6, end_version: None
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG deltalake_core::operations::write] write_execution_plan_with_predicate did not send any batches, no sender.
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T15:49:35Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
Error writing Delta table: Operation not supported: S3 does not support copy-if-not-exists
```

**Comment by ion-elgreco** [comment]
> [2024-09-22T15:49:35Z DEBUG deltalake_aws] S3LogStoreFactory has been asked to create a LogStore without the dynamodb locking provider

Hmmm `[2024-09-22T15:49:35Z DEBUG deltalake_aws] S3LogStoreFactory has been asked to create a LogStore without the dynamodb locking provider` seems the "conditional_put" is not returned into a ConfigKey

**Comment by ion-elgreco** [comment]
@rwhaling can you try: "AWS_CONDITIONAL_PUT"

**Comment by rwhaling** [comment]
Yep.  Same error:

```
Writing Delta table to: s3://test-bucket/test_delta_table
Successfully connected to MinIO
[2024-09-22T16:16:04Z DEBUG deltalake_core::table::builder] creating table builder with s3://test-bucket/test_delta_table
[2024-09-22T16:16:04Z DEBUG deltalake_core::table::builder] build_storage() with s3://test-bucket/test_delta_table
[2024-09-22T16:16:04Z DEBUG deltalake_core::table::builder] Loading a logstore based off the location: Url { scheme: "s3", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("test-bucket")), port: None, path: "/test_delta_table", query: None, fragment: None }
[2024-09-22T16:16:04Z DEBUG deltalake_core::logstore] Found a storage provider for s3:// (s3://test-bucket/test_delta_table)
[2024-09-22T16:16:04Z INFO  object_store::aws::builder] Using Static credential provider
[2024-09-22T16:16:04Z DEBUG deltalake_core::logstore] Found a logstore provider for s3://
[2024-09-22T16:16:04Z DEBUG tracing::span] build_profile_provider;
[2024-09-22T16:16:04Z DEBUG aws_sdk_sts::endpoint_lib] loading default partitions
[2024-09-22T16:16:04Z DEBUG hyper_rustls::config] with_native_roots processed 158 valid and 0 invalid certs
[2024-09-22T16:16:04Z INFO  aws_config::meta::region] load_region; provider=EnvironmentVariableRegionProvider { env: Env(Real) }
[2024-09-22T16:16:04Z INFO  aws_config::meta::region] load_region; provider=ProfileFileRegionProvider { provider_config: ProviderConfig { env: Env(Real), fs: Fs(Real), time_source: SharedTimeSource(SystemTimeSource), http_client: None, sleep_impl: Some(SharedAsyncSleep(TokioSleep)), region: None, use_fips: None, use_dual_stack: None, profile_name_override: None } }
[2024-09-22T16:16:04Z DEBUG aws_runtime::fs_util] loaded home directory src="HOME"
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] load_config_file; file=Default(Config)
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] performing home directory substitution home="/Users/richardwhaling" path="~/.aws/config"
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] home directory expanded before="~/.aws/config" after="/Users/richardwhaling/.aws/config"
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] config file not found path=~/.aws/config
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] config file loaded path=Some("/Users/richardwhaling/.aws/config") size=0
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] load_config_file; file=Default(Credentials)
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] performing home directory substitution home="/Users/richardwhaling" path="~/.aws/credentials"
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] home directory expanded before="~/.aws/credentials" after="/Users/richardwhaling/.aws/credentials"
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] config file not found path=~/.aws/credentials
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] config file loaded path=Some("/Users/richardwhaling/.aws/credentials") size=0
[2024-09-22T16:16:04Z DEBUG tracing::span] build_profile_token_provider;
[2024-09-22T16:16:04Z DEBUG aws_runtime::fs_util] loaded home directory src="HOME"
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] load_config_file; file=Default(Config)
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] performing home directory substitution home="/Users/richardwhaling" path="~/.aws/config"
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] home directory expanded before="~/.aws/config" after="/Users/richardwhaling/.aws/config"
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] config file not found path=~/.aws/config
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] config file loaded path=Some("/Users/richardwhaling/.aws/config") size=0
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] load_config_file; file=Default(Credentials)
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] performing home directory substitution home="/Users/richardwhaling" path="~/.aws/credentials"
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] home directory expanded before="~/.aws/credentials" after="/Users/richardwhaling/.aws/credentials"
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] config file not found path=~/.aws/credentials
[2024-09-22T16:16:04Z DEBUG aws_runtime::env_config::source] config file loaded path=Some("/Users/richardwhaling/.aws/credentials") size=0
[2024-09-22T16:16:04Z DEBUG deltalake_aws] S3LogStoreFactory has been asked to create a LogStore without the dynamodb locking provider
[2024-09-22T16:16:04Z DEBUG reqwest::connect] starting new connection: http://localhost:9000/
[2024-09-22T16:16:04Z DEBUG hyper_util::client::legacy::connect::dns] resolving host="localhost"
[2024-09-22T16:16:04Z DEBUG hyper_util::client::legacy::connect::http] connecting to [::1]:9000
[2024-09-22T16:16:04Z DEBUG hyper_util::client::legacy::connect::http] connected to [::1]:9000
[2024-09-22T16:16:04Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
[2024-09-22T16:16:04Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
...
[2024-09-22T16:16:04Z DEBUG hyper_util::client::legacy::pool] reuse idle connection for ("http", localhost:9000)
[2024-09-22T16:16:04Z DEBUG hyper_util::client::legacy::pool] pooling idle connection for ("http", localhost:9000)
Error writing Delta table: Operation not supported: S3 does not support copy-if-not-exists
```

**Comment by ion-elgreco** [comment]
@rwhaling looking into it, give me a sec

**Comment by ion-elgreco** [comment]
@rwhaling can you compile this version: https://github.com/delta-io/delta-rs/pull/2896 and try again

**Comment by rwhaling** [comment]
@ion-elgreco - following the instructions here: https://github.com/delta-io/delta-rs/blob/main/CONTRIBUTING.md

But struggling with getting pyarrow built - 

```
  CMake Error at CMakeLists.txt:266 (find_package):
    By not providing "FindArrow.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "Arrow", but
    CMake did not find one.
  
    Could not find a package configuration file provided by "Arrow" with any of
    the following names:
  
      ArrowConfig.cmake
      arrow-config.cmake
  
    Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
    "Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
    provides a separate development package or SDK, be sure it has been
    installed.
```

Sorry, I feel like I'm just bumping into one yak-shave after another.  Going to keep working on this - would like to invest the time and get a proper dev environment working over here.

**Comment by ion-elgreco** [comment]
@rwhaling it's probably that because you usually don't have to build pyarrow yourself

**Comment by ion-elgreco** [comment]
In the mean time you can use aws_conditional_put in lowercase and it should work

**Comment by rwhaling** [comment]
Thanks so much @ion-elgreco!  
Can confirm that "aws_conditional_put" works, and will update that in my doc PR.

FWIW - I think I did manage to build pyarrow and then build the deltalake wheel, and I think I'm still getting the same error?  But I don't totally trust my various hacks around the wheel installation yet, so don't want to pull you into yet another rabbit hole today - will hack on that a little more over the next few days - 
thanks again!

**Comment by rwhaling** [comment]
@ion-elgreco @rtyler - will take another pass at this.  Curious how fast y'all like to move with releases - if https://github.com/delta-io/delta-rs/pull/2896 is going to go out soon, I might just hold on this and make the docs a little cleaner with `"AWS_CONDITIONAL_PUT"`

Do y'all normally sync doc/site updates with releases, or do they go live at a faster clip?

**Review by rtyler — DISMISSED** [review]

**Comment by ion-elgreco** [comment]
@rwhaling could you resolve the merge conflict?

**Comment by rwhaling** [comment]
yep, on it

**Comment by rwhaling** [comment]
@ion-elgreco @rtyler should be good to go?  lmk if I bungled something, I'm still clunky working across forks.

**Comment by ion-elgreco** [comment]
@rwhaling great, can you also squash the commits into one commit? Easiest would be to just do git push --force-with-lease

**Comment by rwhaling** [comment]
@rtyler is too fast haha, thank y'all!

**Pull request merged**
