### PR TITLE
Refactor azure storage with crate updates

### PR DESCRIPTION
**Pull request by roeap**
# Description

With the latest version of the azure SDKs some annoyances got fixed. specifically, list now returns something `Send`able, which allows us to significantly simplify the `list_objs` method. Secondly the errors are no longer a deeply nested nightmare 😆.

Also added a test for validating that service principal access works (#609) - currently i am guessing the issues encountered there are more related to #643

# Related Issue(s)

validate the SP access works for #609

# Documentation

### CODE REVIEW

**Comment by Blajda** [comment]
Hi @roeap you can remove `tokio-util` from the dependency list since it was introduced for the !Send issue.

**Comment by roeap** [comment]
Thanks @Blajda  - always happy to be able to slim down dependencies 😆

**Review by wjones127 — DISMISSED** [review]
This is a great cleanup! LGTM.

**Comment by roeap** [comment]
@wjones127 - we saw failing CI due to windows runners running out of disk space. Based on this comment https://github.com/pola-rs/polars/pull/3122#issuecomment-1096564533 I switched to using Swatinem/rust-cache, which seems to do some nice things around managing cache size and utilization.

Right now builds are passing again, but this could just be related to using a "fresh" cache, we'll have to keep an eye on it.

Could you have another look?

**Review by wjones127 — APPROVED** [review]
This looks like it helped Polars and they are still using it, so should be good. I'll keep on eye on that CI job.

**Pull request merged**
