### PR TITLE
Release of the Python binding version 0.5.8

### PR DESCRIPTION
**Pull request by fvaleye**
# Description
- Bump version of maturin to `0.12.19`
- Update the rust dependencies
- Prepare the release of the new version of the Python binding 0.5.8

### CODE REVIEW

**Comment by roeap** [comment]
@fvaleye - i am working on a fix for #600 that should be ready very soon. 

@wjones127 also mentioned hoping to get #625 in before a release.

Could we hold off releasing until those are done?

**Comment by fvaleye** [comment]
Sure @roeap 👍 

When it's done, I will merge your branches into this one!

**Comment by wjones127** [comment]
Also note #651.

**Comment by wjones127** [comment]
@fvaleye I believe all blocking PRs have been merged. Thanks for waiting!

**Review by houqp — APPROVED** [review]

**Pull request merged**
