### PR TITLE
Add contributing page with roadmap and good first issues link

### PR DESCRIPTION
**Pull request by wjones127**
# Description

This is the published version of the google doc https://docs.google.com/document/d/1iKVdnilMCS6qziBBVohXw2-UX_Ld2K6AAjLTZHcYhQ0/edit#heading=h.iezbyetoxtf

# Related Issue(s)

# Documentation

### CODE REVIEW

**Comment by houqp** [comment]
This is a very exciting roadmap!

**Review by houqp — APPROVED** [review]

**Review by fvaleye — APPROVED** [review]
Great! Thx @wjones127

**Comment by dennyglee** [comment]
This is awesome @wjones127! Quick note, just created the bitly link pointing to this doc going forward: https://go.delta.io/rust-roadmap.  HTH!

**Comment by wjones127** [comment]
> This is awesome @wjones127! Quick note, just created the bitly link pointing to this doc going forward: https://go.delta.io/rust-roadmap. HTH!

Oh actually, could that point to https://github.com/delta-io/delta-rs/blob/main/CONTRIBUTING.md#roadmap-2022h2 ?

We were planning on archiving that google doc, and considering the page in GitHub to be the public-facing version.

**Comment by dennyglee** [comment]
@wjones127 done!  you got it!

**Pull request merged**
