### PR TITLE
Updated the object_store version to 0.5

### LINKED ISSUE #781: Remove cargo.patch for `object_store` crate
# Description

Currently we patch the version of the `object_store` crate to take advantage of the removed S3 and azure SDKs, once the new version is published (apache/arrow-rs#2620), we need to remember to remove the patch from Cargo.,toml

**Use Case**

**Related Issue(s)**

### PR DESCRIPTION
**Pull request by kesavkolla**
# Description
Updated the obect_store crate to latest version 0.5

# Related Issue(s)

# Documentation

### CODE REVIEW

**Comment by roeap** [comment]
@kesavkolla, thanks for the PR!. There is a few more adjustments needed though. We also need to update ci/cd as in the new version the gcs client no longer uses an unsecured connection, but rather fake-gcs needs to run with http. The services in github action do not provide that config. The object_store integration tests are a good reference on how to do this. 

Also, the builder for gcs slightly changed ...

**Comment by kesavkolla** [comment]
@roeap I am so sorry; I am not familiar with github workflows. The object_store at least has some docker commands to run the fake-gcs server. In this repo there is no docker run command.

**Comment by roeap** [comment]
exactly, right now we use the github action integration for running services right now. However this does not have an option to pass in alternative args. So we have to switch to running the services "manually" as is done in object_store right now. Here we would probably adjust the docker-compose file and just start that before running integration tests.

**Comment by roeap** [comment]
superseded  by #814

**Pull request closed without merging**
