### PR TITLE
Support read subset of columns in Python API.

### LINKED ISSUE #283: Support read subset of columns in Python API
# Description

In machine learning tasks, we often create very "wide" delta datasets with a large number of features. When reading this kind of datasets, it will be more efficient to support reading a subset of columns. Parquet format support this feature naturally, we can use the API from Pyarrow to implement this feature.

Reference: https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Dataset.html#pyarrow.dataset.Dataset.to_table

**Use Case**

User can specify subset of columns when reading delta datasets like this:

```
dt = DeltaTable(table_path)
dt.to_pyarrow_dataset().to_table(columns=["value", "day"])
```

**Related Issue(s)**

N/A

### PR DESCRIPTION
**Pull request by zijie0**
# Description

Leverage pyarrow API to implement column projection while reading datasets.

# Related Issue(s)

- closes #283 

# Documentation

### CODE REVIEW

**Comment by fvaleye** [comment]
Thank you @zijie0.

LGTM!

The issue of `mypy` check in the CI will be fixed [here](https://github.com/delta-io/delta-rs/pull/285).
When it's merged, we will make sure that the CI is green for your PR before merging it!

**Comment by zijie0** [comment]
Thank you for your review @fvaleye .
I will merge your PR into my branch once it is approved.

**Comment by houqp** [comment]
Thanks @zijie0 for the contribution 👍

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
time for a new python release to test our docs release pipeline :)

**Pull request merged**
