### PR TITLE
Simplify the Store Backend Configuration code

### PR DESCRIPTION
**Pull request by mrjoe7**
# Description
Purpose of this PR is to simplify the Store Backend Configuration code by removing ObjectStoreImpl enum.

### CODE REVIEW

**Comment by roeap** [comment]
thanks @mrjoe7 - this looks like a great refactor!

There seem to be some merge conflicts after a recent merge to main. Could you fix those, so I can trigger CI?

**Comment by mrjoe7** [comment]
@roeap any idea why python 3.10 tests is giving me Timeout error? Because I have no idea why it happened.

**Review by roeap — APPROVED** [review]
Looking great, thanks!

**Comment by roeap** [comment]
@mrjoe7 - don't worry about the timeout, it's unrelated..

**Pull request merged**
