### PR TITLE
fix: respect case sensitivity on operations

### LINKED ISSUE #1797: DeltaTable Merge throws in merging if there are uppercase in Schema.
# Environment

**Delta-rs version**:   deltalake==0.12.0

**Binding**: 

**Environment**:
- **Cloud provider**:
- **OS**:
- **Other**: python

***
# Bug

**What happened**:
If deltatable schema has attribute with upper case in them, then the merge throws Generic deltatable error stating field not found
**What you expected to happen**:
The Deltatable merge operation should have been performed.
**How to reproduce it**:
Sample code:- 

```python
from deltalake import DeltaTable, write_deltalake
from datetime import datetime
import polars as pl

df = pl.DataFrame(
    {
        "Sales_order_id": ["1000", "1001", "1002", "1003"],
        "product": ["bike", "scooter", "car", "motorcycle"],
        "order_date": [
            datetime(2023, 1, 1),
            datetime(2023, 1, 5),
            datetime(2023, 1, 10),
            datetime(2023, 2, 1),
        ],
        "sales_price": [120.25, 2400, 32000, 9000],
        "paid_by_customer": [True, False, False, True],
    }
)
print(df)
df.write_delta("sales_orders_old", mode="append")

new_data = pl.DataFrame(
    {
        "Sales_order_id": ["1002", "1004"],
        "product": ["car", "car"],
        "order_date": [datetime(2023, 1, 10), datetime(2023, 2, 5)],
        "sales_price": [30000.0, 40000.0],
        "paid_by_customer": [True, True],
    }
)

from polars.io.delta import _convert_pa_schema_to_delta

dt = DeltaTable("sales_orders_old")
source = new_data.to_arrow()
delta_schema = _convert_pa_schema_to_delta(source.schema)
source = source.cast(delta_schema)

(
    dt.merge(
        source=source,
        predicate="s.Sales_order_id = t.Sales_order_id",
        source_alias="s",
        target_alias="t",
    )
    .when_matched_update_all()
    .when_not_matched_insert_all()
    .execute()
)
```

This will throw:-  DeltaError: Generic DeltaTable error: Schema error: No field named s.sales_order_id.
**More details**:

Referenced from this blog post https://delta.io/blog/2023-10-22-delta-rs-python-v0.12.0/

### PR DESCRIPTION
**Pull request by Blajda**
# Description
By default when Datafusion parses sql expressions it converts columns references to lower case. The `Into` trait for `Column` will also convert the column name to lower case. This is an issue since column names are case sensitive in the delta protocol and it has prevented users from using various operation with the python bindings. 

This is fixed by configuring Datafusion's sql parser to not normalize identifiers and any public references to `Column` are replaced with `DeltaColumn` which will keep capitalization. 

# Related Issue(s)
- closes #1797

### CODE REVIEW

**Comment by rtyler** [comment]
@Blajda this seems reasonable to me, are you ready to pull it out of draft?

**Review by ion-elgreco — APPROVED** [review]
Looks good! Great fix :)

**Review by rtyler — APPROVED** [review]

**Comment by rtyler** [comment]
@Blajda since you contributed this fix, is this an urgent thing you would like to depend on (i.e. I need to backport to the 0.16 release branch) or are you okay with it going out in 0.17 in a few weeks?

**Comment by Blajda** [comment]
I'm okay with this going out in 0.17. Thanks!

**Comment by cesar-vermeulen** [comment]
Is there any update on this? This issue is currently blocking us on implementing the merge features in delta-rs

**Comment by ion-elgreco** [comment]
@cesar-vermeulen which version are you using? because this is already released

**Pull request merged**
