### PR TITLE
feat: add metadata for deletion vectors

### PR DESCRIPTION
**Pull request by aersam**
# Description
This just adds the deletion vector metadata to the actions. It does not interpret those yet, reading / writing deletion vectors is not supported with this. Still it enables use cases where you use delta-rs just for metadata retrieval

I have to add that I'm still learning rust and I expect this to take some iterations until code quality is sufficient

# Related Issue(s)
Part of #1094 : Adds the required metadata

# Documentation

https://github.com/delta-io/delta/blob/master/PROTOCOL.md#deletion-vectors

### CODE REVIEW

**Comment by aersam** [comment]
As a next step, one could add the absolute path of the deletion vector to the get_actions method. This requires a dependency on z85

**Comment by aersam** [comment]
I'll update the PR in the next days to address the checks

**Comment by aersam** [comment]
> I'll update the PR in the next days to address the checks

Should be ok now

**Review by wjones127 — CHANGES_REQUESTED** [review]
Hi @aersam! Thanks for making this PR.

I think you need to run format, and then I have one requested change. Otherwise looks pretty good.

**Comment by aersam** [comment]
> Hi @aersam! Thanks for making this PR.
> 
> I think you need to run format, and then I have one requested change. Otherwise looks pretty good.

That sounds good! I tried making the change in an idiomatic way and I hope I did nothing too bad :) Though I'm new to rust it feels a bit like "Programming done right", but I'm sure I still have to learn a lot there

**Review by wjones127 — APPROVED** [review]

**Comment by wjones127** [comment]
@aersam Sorry for the delay in re-reviewing. Looks good. Just needs to be rebased and pass CI to merge :)

**Comment by aersam** [comment]
> @aersam Sorry for the delay in re-reviewing. Looks good. Just needs to be rebased and pass CI to merge :)

No problem, thanks for re-reviewing! I clicked that "Sync" Button :) , should be rebased now

**Pull request merged**
