### PR TITLE
feat: override dynamodb config

### LINKED ISSUE #2287: Accommodate separate set of credentials to access DynamoDB
# Description
When using an S3 compatible storage other than AWS S3, one has a set of access and secret key for the storage and another set for the DynamoDB. In this case, we need an option to provide separate credentials for DynamoDB access.

**Use Case**
Concurrent writes to an S3 compatible storage that does not share the credentials as DynamoDB.

**Related Issue(s)**

### LINKED ISSUE #2497: [deltalake_aws] Allow passing AWS_SESSION_TOKEN and other credentials more directly to DynamoDB client.
# Description

My understanding of the code [here](https://github.com/delta-io/delta-rs/blob/81593e919497221a1a08bf8db9d20e8e4a39a8a6/crates/aws/src/storage.rs#L146-L153) is that AWS_SESSION_TOKEN, AWS_SECRET_ACCESS_KEY, and AWS_ACCESS_KEY_ID are assigned to environment variables, and later inferred by the S3 client and the DynamoDB client. It would be nicer if they could be passed directly to these clients without being part of the process's environment.

I think an ideal solution would allow me to configure my own object store and dynamo client, and provide those when registering a table.

**Use Case**

My process is a big monolith with a bunch of stuff in it, completely unrelated to me. Many different identities are used in this process for many different purposes. Environment variables are a single global namespace, so it would be dangerous to plug my credentials in it.

**Related Issue(s)**

### PR DESCRIPTION
**Pull request by thomas-chauvet**
# Description

This PR add the possibility to override dynamoDB configuration via `storage_options`:

- `AWS_ENDPOINT_URL_DYNAMODB` overrides `AWS_ENDPOINT_URL`,
- `AWS_REGION_DYNAMODB` overrides `AWS_REGION`,
- `AWS_ACCESS_KEY_ID_DYNAMODB` overrides `AWS_ACCESS_KEY_ID`,
- `AWS_SECRET_ACCESS_KEY_DYNAMODB` overrides `AWS_SECRET_ACCESS_KEY`.

It solves cases where we use an S3-compatible storage without mutual exclusion but we want to use DynamoDB anyway as a locking provider.
It also solves the case where we want to pass different credentials or region for S3 and dynamoDB.

# Related Issue(s)
- closes #2497 
- closes #2287 

# Documentation

Documentation has been updated to explain how to override configuration.

### CODE REVIEW

**Review by rtyler — DISMISSED** [review]

**Comment by thomas-chauvet** [comment]
@rtyler thanks for your quick review! I've just fixed a small equality in test. I've made a workaround before and I've left it in the code. It is now properly fixed. Thanks!

**Comment by ion-elgreco** [comment]
@thomas-chauvet @rtyler This might be short lived, if we can get delta-rs bumped soon to the new objectstore release. I would like us to default using putIfAbsent by default for any S3 implementation, then it's up to users who use S3 which does not support this, to set copyIfNotExists or allow unsafe_rename

**Comment by thomas-chauvet** [comment]
Does this mean that locking provider will be definitely remove from delta-rs?

**Comment by ion-elgreco** [comment]
> Does this mean that locking provider will be definitely remove from delta-rs?

Not per se, but the value of a locking provider is quite minimal unless you still use an S3 implementation like LakeFS that doesn't have these request headers yet

**Comment by rtyler** [comment]
@ion-elgreco I don't expect the DynamoDB log store code to go away for at least 3-6 months, even if we had the `putIfAbsent` support today, I would want to keep the support around because existing deployments using DynamoDB will not all be ready to migrate 100%. 

I see value in adding these parameters until such a time when all DynamoDB code is removed from delta-rs, which currently has no scheduled time.

**Comment by ion-elgreco** [comment]
> @ion-elgreco I don't expect the DynamoDB log store code to go away for at least 3-6 months, even if we had the `putIfAbsent` support today, I would want to keep the support around because existing deployments using DynamoDB will not all be ready to migrate 100%. 
> 
> I see value in adding these parameters until such a time when all DynamoDB code is removed from delta-rs, which currently has no scheduled time.

For sure, we should keep it for some time!

**Review by ion-elgreco — APPROVED** [review]

**Comment by thomas-chauvet** [comment]
Thanks for the merge!

**Pull request merged**
